// AUTO-GENERATED by run_demo.py -> src/audit/webapp_export.py
// Source: submission_artifacts/ (this run). Do not hand-edit — it is
// overwritten every time the demo runs. Every field here was read back
// off disk from files the pipeline itself produced.
window.TDES_DATA = {
  "meta": {
    "run_id": "run_A",
    "branch_id": "main",
    "context_len": 128,
    "total_steps": 18,
    "checkpoint_every": 5,
    "crash_at_step": 12,
    "resume_from_step": 10,
    "replay_start": 5,
    "replay_end": 10,
    "total_docs": 27,
    "admitted_docs": 24,
    "blocked_docs": 3,
    "test_count": 16,
    "generated_at": "2026-08-07T05:55:57Z"
  },
  "evidence": {
    "tokenizer_integrity": {
      "result": "PASS",
      "description": "tokenizer_sha=tok_27b6a09dd8613291",
      "evidence": "submission_artifacts/tokenizer_spec.json"
    },
    "eval_firewall": {
      "result": "PASS",
      "description": "3 eval shards blocked, 0 violations",
      "evidence": "submission_artifacts/manifests/manifest_summary.json"
    },
    "packing_correctness": {
      "result": "PASS",
      "description": "structure_preserving: 82.7% util, agentic masks applied",
      "evidence": "submission_artifacts/ledgers/packing_report.json"
    },
    "crash_recovery": {
      "result": "PASS",
      "description": "next_batch=run_A_batch_0010 matched, hash verified",
      "evidence": "submission_artifacts/checkpoints/ckpt_run_A_main_step00010/meta.json"
    },
    "replay": {
      "result": "PASS",
      "description": "All 5 replayed batches hash-matched original",
      "evidence": "submission_artifacts/ledgers/replay_hashes.json"
    },
    "opus_audit_trail": {
      "result": "PASS",
      "description": "12 decisions logged, 2 floor overrides",
      "evidence": "submission_artifacts/ledgers/opus_decisions.jsonl"
    },
    "mixture_compliance": {
      "result": "PASS",
      "description": "Curriculum stages executed, floors enforced",
      "evidence": "submission_artifacts/ledgers/mixture_actual.json"
    },
    "learning_trace": {
      "result": "PASS",
      "description": "Loss linked to 16 source documents",
      "evidence": "submission_artifacts/ledgers/doc_loss_summary.json"
    },
    "throughput": {
      "result": "PASS",
      "description": "packing=82.7%, avg_tps=696",
      "evidence": "submission_artifacts/performance.json"
    }
  },
  "performance": {
    "total_steps": 17,
    "average_loss": 11.516923,
    "final_loss": 11.513885,
    "average_tokens_per_sec": 696.4,
    "packing_policy": "structure_preserving",
    "packing_utilization_pct": 82.74,
    "useful_tokens_total": 2436,
    "num_packed_sequences": 23,
    "context_len": 128,
    "generated_at": "2026-08-07T05:55:57Z"
  },
  "packingReport": {
    "pad_each_doc": {
      "policy": "pad_each_doc",
      "num_sequences": 24,
      "context_len": 128,
      "total_positions": 3072,
      "useful_tokens": 2436,
      "utilization_pct": 79.3,
      "avg_loss_bearing": 101.5
    },
    "concat_and_chop": {
      "policy": "concat_and_chop",
      "num_sequences": 38,
      "context_len": 128,
      "total_positions": 4864,
      "useful_tokens": 4795,
      "utilization_pct": 98.58,
      "avg_loss_bearing": 126.18
    },
    "greedy_pack": {
      "policy": "greedy_pack",
      "num_sequences": 23,
      "context_len": 128,
      "total_positions": 2944,
      "useful_tokens": 2436,
      "utilization_pct": 82.74,
      "avg_loss_bearing": 105.91
    },
    "best_fit_pack": {
      "policy": "best_fit_pack",
      "num_sequences": 23,
      "context_len": 128,
      "total_positions": 2944,
      "useful_tokens": 2436,
      "utilization_pct": 82.74,
      "avg_loss_bearing": 105.91
    },
    "structure_preserving": {
      "policy": "structure_preserving",
      "num_sequences": 23,
      "context_len": 128,
      "total_positions": 2944,
      "useful_tokens": 2436,
      "utilization_pct": 82.74,
      "avg_loss_bearing": 105.91
    }
  },
  "manifests": [
    {
      "shard_id": "shard_018d7f19af9f",
      "lane": "agentic",
      "token_count": 275,
      "admission": "admitted",
      "admission_score": 87,
      "language": "en",
      "is_eval": false
    },
    {
      "shard_id": "shard_02e768a004fe",
      "lane": "web",
      "token_count": 71,
      "admission": "admitted",
      "admission_score": 87,
      "language": "en",
      "is_eval": false
    },
    {
      "shard_id": "shard_19af3f3c5e81",
      "lane": "web",
      "token_count": 70,
      "admission": "admitted",
      "admission_score": 87,
      "language": "en",
      "is_eval": false
    },
    {
      "shard_id": "shard_36b729afe1c8",
      "lane": "indic",
      "token_count": 435,
      "admission": "admitted",
      "admission_score": 87,
      "language": "pa",
      "is_eval": false
    },
    {
      "shard_id": "shard_59f2f6f94b82",
      "lane": "agentic",
      "token_count": 259,
      "admission": "admitted",
      "admission_score": 87,
      "language": "en",
      "is_eval": false
    },
    {
      "shard_id": "shard_62ed495fa711",
      "lane": "code",
      "token_count": 188,
      "admission": "admitted",
      "admission_score": 87,
      "language": "en",
      "is_eval": false
    },
    {
      "shard_id": "shard_6a5650ccbda8",
      "lane": "code",
      "token_count": 149,
      "admission": "admitted",
      "admission_score": 87,
      "language": "en",
      "is_eval": false
    },
    {
      "shard_id": "shard_7bf029ec862f",
      "lane": "agentic",
      "token_count": 145,
      "admission": "admitted",
      "admission_score": 87,
      "language": "en",
      "is_eval": false
    },
    {
      "shard_id": "shard_86e8eafa0458",
      "lane": "agentic",
      "token_count": 394,
      "admission": "admitted",
      "admission_score": 87,
      "language": "en",
      "is_eval": false
    },
    {
      "shard_id": "shard_8f703fea119c",
      "lane": "web",
      "token_count": 75,
      "admission": "blocked",
      "admission_score": 51,
      "language": "en",
      "is_eval": true
    },
    {
      "shard_id": "shard_99f254612f80",
      "lane": "code",
      "token_count": 163,
      "admission": "admitted",
      "admission_score": 87,
      "language": "en",
      "is_eval": false
    },
    {
      "shard_id": "shard_a9d1d77017bf",
      "lane": "indic",
      "token_count": 289,
      "admission": "admitted",
      "admission_score": 87,
      "language": "bn",
      "is_eval": false
    },
    {
      "shard_id": "shard_aff6f3ffce36",
      "lane": "code",
      "token_count": 98,
      "admission": "admitted",
      "admission_score": 87,
      "language": "en",
      "is_eval": false
    },
    {
      "shard_id": "shard_be4b7e074012",
      "lane": "web",
      "token_count": 70,
      "admission": "admitted",
      "admission_score": 87,
      "language": "en",
      "is_eval": false
    },
    {
      "shard_id": "shard_c1d0d139ede8",
      "lane": "code",
      "token_count": 123,
      "admission": "admitted",
      "admission_score": 87,
      "language": "en",
      "is_eval": false
    },
    {
      "shard_id": "shard_c7df4d18ebfe",
      "lane": "indic",
      "token_count": 499,
      "admission": "admitted",
      "admission_score": 87,
      "language": "te",
      "is_eval": false
    },
    {
      "shard_id": "shard_ca51f610fcf6",
      "lane": "web",
      "token_count": 51,
      "admission": "blocked",
      "admission_score": 51,
      "language": "en",
      "is_eval": true
    },
    {
      "shard_id": "shard_cb052d0e3f0f",
      "lane": "indic",
      "token_count": 280,
      "admission": "admitted",
      "admission_score": 87,
      "language": "mr",
      "is_eval": false
    },
    {
      "shard_id": "shard_cbfb745e4a50",
      "lane": "code",
      "token_count": 143,
      "admission": "admitted",
      "admission_score": 87,
      "language": "en",
      "is_eval": false
    },
    {
      "shard_id": "shard_cd066b15d7ea",
      "lane": "indic",
      "token_count": 330,
      "admission": "admitted",
      "admission_score": 87,
      "language": "hi",
      "is_eval": false
    },
    {
      "shard_id": "shard_ce5162b5687c",
      "lane": "web",
      "token_count": 79,
      "admission": "admitted",
      "admission_score": 87,
      "language": "en",
      "is_eval": false
    },
    {
      "shard_id": "shard_d13ef297215a",
      "lane": "web",
      "token_count": 62,
      "admission": "admitted",
      "admission_score": 87,
      "language": "en",
      "is_eval": false
    },
    {
      "shard_id": "shard_d537935386b8",
      "lane": "indic",
      "token_count": 459,
      "admission": "admitted",
      "admission_score": 87,
      "language": "kn",
      "is_eval": false
    },
    {
      "shard_id": "shard_e586b6a100e7",
      "lane": "web",
      "token_count": 67,
      "admission": "admitted",
      "admission_score": 87,
      "language": "en",
      "is_eval": false
    },
    {
      "shard_id": "shard_f56131669784",
      "lane": "web",
      "token_count": 71,
      "admission": "admitted",
      "admission_score": 87,
      "language": "en",
      "is_eval": false
    },
    {
      "shard_id": "shard_f8dea85b952b",
      "lane": "web",
      "token_count": 52,
      "admission": "blocked",
      "admission_score": 51,
      "language": "en",
      "is_eval": true
    },
    {
      "shard_id": "shard_fe52b833472e",
      "lane": "web",
      "token_count": 52,
      "admission": "admitted",
      "admission_score": 87,
      "language": "en",
      "is_eval": false
    }
  ],
  "opusDecisions": [
    {
      "step": 0,
      "batch_id": "run_A_batch_0000",
      "lane": "indic",
      "decision": "defer",
      "score": 0.6493,
      "reason": "score=0.649 in defer zone [0.594,0.699)",
      "token_count": 128,
      "timestamp": "2026-08-07T05:55:40Z"
    },
    {
      "step": 1,
      "batch_id": "run_A_batch_0001",
      "lane": "indic",
      "decision": "defer",
      "score": 0.6596,
      "reason": "score=0.660 in defer zone [0.594,0.699)",
      "token_count": 128,
      "timestamp": "2026-08-07T05:55:40Z"
    },
    {
      "step": 2,
      "batch_id": "run_A_batch_0002",
      "lane": "indic",
      "decision": "defer",
      "score": 0.6474,
      "reason": "score=0.647 in defer zone [0.594,0.699)",
      "token_count": 128,
      "timestamp": "2026-08-07T05:55:40Z"
    },
    {
      "step": 3,
      "batch_id": "run_A_batch_0003",
      "lane": "indic",
      "decision": "defer",
      "score": 0.6459,
      "reason": "score=0.646 in defer zone [0.594,0.699)",
      "token_count": 128,
      "timestamp": "2026-08-07T05:55:41Z"
    },
    {
      "step": 4,
      "batch_id": "run_A_batch_0004",
      "lane": "code",
      "decision": "accept",
      "score": 0.7045,
      "reason": "score=0.704 >= threshold=0.699",
      "token_count": 124,
      "timestamp": "2026-08-07T05:55:41Z"
    },
    {
      "step": 5,
      "batch_id": "run_A_batch_0005",
      "lane": "web",
      "decision": "reject",
      "score": 0.5108,
      "reason": "score=0.511 < defer_threshold=0.594",
      "token_count": 121,
      "timestamp": "2026-08-07T05:55:43Z"
    },
    {
      "step": 6,
      "batch_id": "run_A_batch_0006",
      "lane": "indic",
      "decision": "accept",
      "score": 0.6489,
      "reason": "protected_floor_override: indic below 12%",
      "token_count": 128,
      "timestamp": "2026-08-07T05:55:43Z"
    },
    {
      "step": 7,
      "batch_id": "run_A_batch_0007",
      "lane": "agentic",
      "decision": "accept",
      "score": 0.7265,
      "reason": "protected_floor_override: agentic below 2%",
      "token_count": 95,
      "timestamp": "2026-08-07T05:55:44Z"
    },
    {
      "step": 8,
      "batch_id": "run_A_batch_0008",
      "lane": "web",
      "decision": "reject",
      "score": 0.5369,
      "reason": "score=0.537 < defer_threshold=0.594",
      "token_count": 72,
      "timestamp": "2026-08-07T05:55:44Z"
    },
    {
      "step": 9,
      "batch_id": "run_A_batch_0009",
      "lane": "code",
      "decision": "accept",
      "score": 0.7746,
      "reason": "score=0.775 >= threshold=0.699",
      "token_count": 128,
      "timestamp": "2026-08-07T05:55:44Z"
    },
    {
      "step": 10,
      "batch_id": "run_A_batch_0010",
      "lane": "web",
      "decision": "reject",
      "score": 0.523,
      "reason": "score=0.523 < defer_threshold=0.594",
      "token_count": 72,
      "timestamp": "2026-08-07T05:55:46Z"
    },
    {
      "step": 11,
      "batch_id": "run_A_batch_0011",
      "lane": "agentic",
      "decision": "accept",
      "score": 0.7009,
      "reason": "score=0.701 >= threshold=0.699",
      "token_count": 97,
      "timestamp": "2026-08-07T05:55:46Z"
    }
  ],
  "consumption": [
    {
      "step": 0,
      "batch_id": "run_A_batch_0000",
      "shard_ids": [
        "shard_36b729afe1c8"
      ],
      "doc_ids": [
        "doc_0016"
      ],
      "token_count": 128,
      "useful_tokens": 128,
      "loss_bearing_tokens": 128,
      "lane": "indic",
      "lane_breakdown": {
        "indic": 128
      },
      "policy": "structure_preserving",
      "utilization": 1.0,
      "timestamp": "2026-08-07T05:55:40Z"
    },
    {
      "step": 1,
      "batch_id": "run_A_batch_0001",
      "shard_ids": [
        "shard_c7df4d18ebfe"
      ],
      "doc_ids": [
        "doc_0015"
      ],
      "token_count": 128,
      "useful_tokens": 128,
      "loss_bearing_tokens": 128,
      "lane": "indic",
      "lane_breakdown": {
        "indic": 128
      },
      "policy": "structure_preserving",
      "utilization": 1.0,
      "timestamp": "2026-08-07T05:55:40Z"
    },
    {
      "step": 2,
      "batch_id": "run_A_batch_0002",
      "shard_ids": [
        "shard_d537935386b8"
      ],
      "doc_ids": [
        "doc_0018"
      ],
      "token_count": 128,
      "useful_tokens": 128,
      "loss_bearing_tokens": 128,
      "lane": "indic",
      "lane_breakdown": {
        "indic": 128
      },
      "policy": "structure_preserving",
      "utilization": 1.0,
      "timestamp": "2026-08-07T05:55:41Z"
    },
    {
      "step": 3,
      "batch_id": "run_A_batch_0003",
      "shard_ids": [
        "shard_cb052d0e3f0f"
      ],
      "doc_ids": [
        "doc_0019"
      ],
      "token_count": 128,
      "useful_tokens": 128,
      "loss_bearing_tokens": 128,
      "lane": "indic",
      "lane_breakdown": {
        "indic": 128
      },
      "policy": "structure_preserving",
      "utilization": 1.0,
      "timestamp": "2026-08-07T05:55:41Z"
    },
    {
      "step": 4,
      "batch_id": "run_A_batch_0004",
      "shard_ids": [
        "shard_c1d0d139ede8"
      ],
      "doc_ids": [
        "doc_0009"
      ],
      "token_count": 128,
      "useful_tokens": 124,
      "loss_bearing_tokens": 124,
      "lane": "code",
      "lane_breakdown": {
        "code": 124
      },
      "policy": "structure_preserving",
      "utilization": 0.9688,
      "timestamp": "2026-08-07T05:55:41Z"
    },
    {
      "step": 6,
      "batch_id": "run_A_batch_0006",
      "shard_ids": [
        "shard_a9d1d77017bf"
      ],
      "doc_ids": [
        "doc_0017"
      ],
      "token_count": 128,
      "useful_tokens": 128,
      "loss_bearing_tokens": 128,
      "lane": "indic",
      "lane_breakdown": {
        "indic": 128
      },
      "policy": "structure_preserving",
      "utilization": 1.0,
      "timestamp": "2026-08-07T05:55:44Z"
    },
    {
      "step": 7,
      "batch_id": "run_A_batch_0007",
      "shard_ids": [
        "shard_7bf029ec862f"
      ],
      "doc_ids": [
        "doc_0023"
      ],
      "token_count": 95,
      "useful_tokens": 95,
      "loss_bearing_tokens": 95,
      "lane": "agentic",
      "lane_breakdown": {
        "agentic": 95
      },
      "policy": "structure_preserving",
      "utilization": 0.7422,
      "timestamp": "2026-08-07T05:55:44Z"
    },
    {
      "step": 9,
      "batch_id": "run_A_batch_0009",
      "shard_ids": [
        "shard_99f254612f80"
      ],
      "doc_ids": [
        "doc_0010"
      ],
      "token_count": 128,
      "useful_tokens": 128,
      "loss_bearing_tokens": 128,
      "lane": "code",
      "lane_breakdown": {
        "code": 128
      },
      "policy": "structure_preserving",
      "utilization": 1.0,
      "timestamp": "2026-08-07T05:55:44Z"
    },
    {
      "step": 11,
      "batch_id": "run_A_batch_0011",
      "shard_ids": [
        "shard_86e8eafa0458"
      ],
      "doc_ids": [
        "doc_0020"
      ],
      "token_count": 97,
      "useful_tokens": 97,
      "loss_bearing_tokens": 97,
      "lane": "agentic",
      "lane_breakdown": {
        "agentic": 97
      },
      "policy": "structure_preserving",
      "utilization": 0.7578,
      "timestamp": "2026-08-07T05:55:47Z"
    },
    {
      "step": 11,
      "batch_id": "run_A_batch_0011",
      "shard_ids": [
        "shard_86e8eafa0458"
      ],
      "doc_ids": [
        "doc_0020"
      ],
      "token_count": 97,
      "useful_tokens": 97,
      "loss_bearing_tokens": 97,
      "lane": "agentic",
      "lane_breakdown": {
        "agentic": 97
      },
      "policy": "structure_preserving",
      "utilization": 0.7578,
      "timestamp": "2026-08-07T05:55:48Z"
    },
    {
      "step": 12,
      "batch_id": "run_A_batch_0012",
      "shard_ids": [
        "shard_6a5650ccbda8"
      ],
      "doc_ids": [
        "doc_0012"
      ],
      "token_count": 128,
      "useful_tokens": 128,
      "loss_bearing_tokens": 128,
      "lane": "code",
      "lane_breakdown": {
        "code": 128
      },
      "policy": "structure_preserving",
      "utilization": 1.0,
      "timestamp": "2026-08-07T05:55:48Z"
    },
    {
      "step": 14,
      "batch_id": "run_A_batch_0014",
      "shard_ids": [
        "shard_aff6f3ffce36"
      ],
      "doc_ids": [
        "doc_0011"
      ],
      "token_count": 128,
      "useful_tokens": 99,
      "loss_bearing_tokens": 99,
      "lane": "code",
      "lane_breakdown": {
        "code": 99
      },
      "policy": "structure_preserving",
      "utilization": 0.7734,
      "timestamp": "2026-08-07T05:55:48Z"
    },
    {
      "step": 15,
      "batch_id": "run_A_batch_0015",
      "shard_ids": [
        "shard_cd066b15d7ea"
      ],
      "doc_ids": [
        "doc_0014"
      ],
      "token_count": 128,
      "useful_tokens": 128,
      "loss_bearing_tokens": 128,
      "lane": "indic",
      "lane_breakdown": {
        "indic": 128
      },
      "policy": "structure_preserving",
      "utilization": 1.0,
      "timestamp": "2026-08-07T05:55:51Z"
    },
    {
      "step": 16,
      "batch_id": "run_A_batch_0016",
      "shard_ids": [
        "shard_018d7f19af9f"
      ],
      "doc_ids": [
        "doc_0022"
      ],
      "token_count": 94,
      "useful_tokens": 94,
      "loss_bearing_tokens": 94,
      "lane": "agentic",
      "lane_breakdown": {
        "agentic": 94
      },
      "policy": "structure_preserving",
      "utilization": 0.7344,
      "timestamp": "2026-08-07T05:55:51Z"
    },
    {
      "step": 19,
      "batch_id": "run_A_batch_0019",
      "shard_ids": [
        "shard_59f2f6f94b82"
      ],
      "doc_ids": [
        "doc_0021"
      ],
      "token_count": 97,
      "useful_tokens": 97,
      "loss_bearing_tokens": 97,
      "lane": "agentic",
      "lane_breakdown": {
        "agentic": 97
      },
      "policy": "structure_preserving",
      "utilization": 0.7578,
      "timestamp": "2026-08-07T05:55:51Z"
    },
    {
      "step": 21,
      "batch_id": "run_A_batch_0021",
      "shard_ids": [
        "shard_62ed495fa711"
      ],
      "doc_ids": [
        "doc_0013"
      ],
      "token_count": 128,
      "useful_tokens": 128,
      "loss_bearing_tokens": 128,
      "lane": "code",
      "lane_breakdown": {
        "code": 128
      },
      "policy": "structure_preserving",
      "utilization": 1.0,
      "timestamp": "2026-08-07T05:55:54Z"
    },
    {
      "step": 22,
      "batch_id": "run_A_batch_0022",
      "shard_ids": [
        "shard_cbfb745e4a50"
      ],
      "doc_ids": [
        "doc_0008"
      ],
      "token_count": 128,
      "useful_tokens": 128,
      "loss_bearing_tokens": 128,
      "lane": "code",
      "lane_breakdown": {
        "code": 128
      },
      "policy": "structure_preserving",
      "utilization": 1.0,
      "timestamp": "2026-08-07T05:55:54Z"
    }
  ],
  "learning": [
    {
      "step": 0,
      "batch_id": "run_A_batch_0000",
      "loss": 11.518407,
      "loss_bearing_tokens": 128,
      "tokens_per_sec": 731.9,
      "perplexity": 100549.6844,
      "lane": "indic",
      "doc_loss_map": {
        "doc_0016": 11.518407
      },
      "timestamp": "2026-08-07T05:55:40Z"
    },
    {
      "step": 1,
      "batch_id": "run_A_batch_0001",
      "loss": 11.517769,
      "loss_bearing_tokens": 128,
      "tokens_per_sec": 665.1,
      "perplexity": 100485.5541,
      "lane": "indic",
      "doc_loss_map": {
        "doc_0015": 11.517769
      },
      "timestamp": "2026-08-07T05:55:40Z"
    },
    {
      "step": 2,
      "batch_id": "run_A_batch_0002",
      "loss": 11.519267,
      "loss_bearing_tokens": 128,
      "tokens_per_sec": 785.6,
      "perplexity": 100636.1868,
      "lane": "indic",
      "doc_loss_map": {
        "doc_0018": 11.519267
      },
      "timestamp": "2026-08-07T05:55:41Z"
    },
    {
      "step": 3,
      "batch_id": "run_A_batch_0003",
      "loss": 11.516045,
      "loss_bearing_tokens": 128,
      "tokens_per_sec": 887.1,
      "perplexity": 100312.3914,
      "lane": "indic",
      "doc_loss_map": {
        "doc_0019": 11.516045
      },
      "timestamp": "2026-08-07T05:55:41Z"
    },
    {
      "step": 4,
      "batch_id": "run_A_batch_0004",
      "loss": 11.515422,
      "loss_bearing_tokens": 124,
      "tokens_per_sec": 650.9,
      "perplexity": 100249.9318,
      "lane": "code",
      "doc_loss_map": {
        "doc_0009": 11.515422
      },
      "timestamp": "2026-08-07T05:55:41Z"
    },
    {
      "step": 6,
      "batch_id": "run_A_batch_0006",
      "loss": 11.514818,
      "loss_bearing_tokens": 128,
      "tokens_per_sec": 767.3,
      "perplexity": 100189.4541,
      "lane": "indic",
      "doc_loss_map": {
        "doc_0017": 11.514818
      },
      "timestamp": "2026-08-07T05:55:44Z"
    },
    {
      "step": 7,
      "batch_id": "run_A_batch_0007",
      "loss": 11.516086,
      "loss_bearing_tokens": 95,
      "tokens_per_sec": 572.2,
      "perplexity": 100316.5945,
      "lane": "agentic",
      "doc_loss_map": {
        "doc_0023": 11.516086
      },
      "timestamp": "2026-08-07T05:55:44Z"
    },
    {
      "step": 9,
      "batch_id": "run_A_batch_0009",
      "loss": 11.513727,
      "loss_bearing_tokens": 128,
      "tokens_per_sec": 842.6,
      "perplexity": 100080.2066,
      "lane": "code",
      "doc_loss_map": {
        "doc_0010": 11.513727
      },
      "timestamp": "2026-08-07T05:55:44Z"
    },
    {
      "step": 11,
      "batch_id": "run_A_batch_0011",
      "loss": 11.520522,
      "loss_bearing_tokens": 97,
      "tokens_per_sec": 574.1,
      "perplexity": 100762.515,
      "lane": "agentic",
      "doc_loss_map": {
        "doc_0020": 11.520522
      },
      "timestamp": "2026-08-07T05:55:47Z"
    },
    {
      "step": 11,
      "batch_id": "run_A_batch_0011",
      "loss": 11.520522,
      "loss_bearing_tokens": 97,
      "tokens_per_sec": 554.0,
      "perplexity": 100762.515,
      "lane": "agentic",
      "doc_loss_map": {
        "doc_0020": 11.520522
      },
      "timestamp": "2026-08-07T05:55:48Z"
    },
    {
      "step": 12,
      "batch_id": "run_A_batch_0012",
      "loss": 11.514878,
      "loss_bearing_tokens": 128,
      "tokens_per_sec": 703.0,
      "perplexity": 100195.4221,
      "lane": "code",
      "doc_loss_map": {
        "doc_0012": 11.514878
      },
      "timestamp": "2026-08-07T05:55:48Z"
    },
    {
      "step": 14,
      "batch_id": "run_A_batch_0014",
      "loss": 11.51759,
      "loss_bearing_tokens": 99,
      "tokens_per_sec": 554.3,
      "perplexity": 100467.5023,
      "lane": "code",
      "doc_loss_map": {
        "doc_0011": 11.51759
      },
      "timestamp": "2026-08-07T05:55:48Z"
    },
    {
      "step": 15,
      "batch_id": "run_A_batch_0015",
      "loss": 11.517296,
      "loss_bearing_tokens": 128,
      "tokens_per_sec": 678.0,
      "perplexity": 100437.9764,
      "lane": "indic",
      "doc_loss_map": {
        "doc_0014": 11.517296
      },
      "timestamp": "2026-08-07T05:55:51Z"
    },
    {
      "step": 16,
      "batch_id": "run_A_batch_0016",
      "loss": 11.5174,
      "loss_bearing_tokens": 94,
      "tokens_per_sec": 600.4,
      "perplexity": 100448.4691,
      "lane": "agentic",
      "doc_loss_map": {
        "doc_0022": 11.5174
      },
      "timestamp": "2026-08-07T05:55:51Z"
    },
    {
      "step": 19,
      "batch_id": "run_A_batch_0019",
      "loss": 11.51948,
      "loss_bearing_tokens": 97,
      "tokens_per_sec": 630.3,
      "perplexity": 100657.6379,
      "lane": "agentic",
      "doc_loss_map": {
        "doc_0021": 11.51948
      },
      "timestamp": "2026-08-07T05:55:51Z"
    },
    {
      "step": 21,
      "batch_id": "run_A_batch_0021",
      "loss": 11.514579,
      "loss_bearing_tokens": 128,
      "tokens_per_sec": 830.5,
      "perplexity": 100165.483,
      "lane": "code",
      "doc_loss_map": {
        "doc_0013": 11.514579
      },
      "timestamp": "2026-08-07T05:55:54Z"
    },
    {
      "step": 22,
      "batch_id": "run_A_batch_0022",
      "loss": 11.513885,
      "loss_bearing_tokens": 128,
      "tokens_per_sec": 810.7,
      "perplexity": 100096.0408,
      "lane": "code",
      "doc_loss_map": {
        "doc_0008": 11.513885
      },
      "timestamp": "2026-08-07T05:55:54Z"
    }
  ],
  "checkpoints": [
    {
      "checkpoint_id": "ckpt_run_A_main_step00005",
      "step": 5,
      "ledger_offset": 5,
      "run_id": "run_A",
      "branch_id": "main",
      "optimizer_lr": 0.001,
      "weights_hash": "weights_0d767a6724f2",
      "rng_state": {},
      "next_expected_batch_offset": 5,
      "saved_at": "2026-08-07T05:55:43Z"
    },
    {
      "checkpoint_id": "ckpt_run_A_main_step00010",
      "step": 10,
      "ledger_offset": 10,
      "run_id": "run_A",
      "branch_id": "main",
      "optimizer_lr": 0.001,
      "weights_hash": "weights_d2a2f8d02a21",
      "rng_state": {},
      "next_expected_batch_offset": 10,
      "saved_at": "2026-08-07T05:55:46Z"
    },
    {
      "checkpoint_id": "ckpt_run_A_main_step00015",
      "step": 15,
      "ledger_offset": 15,
      "run_id": "run_A",
      "branch_id": "main",
      "optimizer_lr": 0.001,
      "weights_hash": "weights_fcc1d27ed228",
      "rng_state": {},
      "next_expected_batch_offset": 15,
      "saved_at": "2026-08-07T05:55:50Z"
    },
    {
      "checkpoint_id": "ckpt_run_A_main_step00020",
      "step": 20,
      "ledger_offset": 20,
      "run_id": "run_A",
      "branch_id": "main",
      "optimizer_lr": 0.001,
      "weights_hash": "weights_dbb55a5b355e",
      "rng_state": {},
      "next_expected_batch_offset": 20,
      "saved_at": "2026-08-07T05:55:53Z"
    },
    {
      "checkpoint_id": "ckpt_run_FORK_experiment_v2_step00010",
      "step": 10,
      "ledger_offset": 10,
      "run_id": "run_FORK",
      "branch_id": "experiment_v2",
      "optimizer_lr": 0.002,
      "weights_hash": "weights_d2a2f8d02a21",
      "rng_state": {},
      "next_expected_batch_offset": 10,
      "saved_at": "2026-08-07T05:55:57Z",
      "forked_from": "ckpt_run_A_main_step00010"
    }
  ],
  "replayHashes": [
    {
      "step": 5,
      "original_batch_id": "run_A_batch_0005",
      "original_hash": "bh_9903e65b8eea1548",
      "replay_batch_id": "run_A_batch_0005",
      "replay_hash": "bh_9903e65b8eea1548",
      "match": true
    },
    {
      "step": 6,
      "original_batch_id": "run_A_batch_0006",
      "original_hash": "bh_8bad92b9ae6c0d59",
      "replay_batch_id": "run_A_batch_0006",
      "replay_hash": "bh_8bad92b9ae6c0d59",
      "match": true
    },
    {
      "step": 7,
      "original_batch_id": "run_A_batch_0007",
      "original_hash": "bh_8c2db90d56f6e431",
      "replay_batch_id": "run_A_batch_0007",
      "replay_hash": "bh_8c2db90d56f6e431",
      "match": true
    },
    {
      "step": 8,
      "original_batch_id": "run_A_batch_0008",
      "original_hash": "bh_5a90fd6a6339a45b",
      "replay_batch_id": "run_A_batch_0008",
      "replay_hash": "bh_5a90fd6a6339a45b",
      "match": true
    },
    {
      "step": 9,
      "original_batch_id": "run_A_batch_0009",
      "original_hash": "bh_28f87ae7c41c0170",
      "replay_batch_id": "run_A_batch_0009",
      "replay_hash": "bh_28f87ae7c41c0170",
      "match": true
    }
  ],
  "mixtureActual": {
    "planned": {
      "web": 0.49,
      "code": 0.18,
      "indic": 0.16,
      "agentic": 0.02,
      "reasoning": 0.06,
      "stem": 0.09
    },
    "actual": {
      "indic": 0.3873,
      "code": 0.3707,
      "agentic": 0.2421
    },
    "floor_compliance": {
      "indic": {
        "floor": 0.12,
        "actual": 0.5904,
        "compliant": true
      },
      "agentic": {
        "floor": 0.02,
        "actual": 0.1771,
        "compliant": true
      }
    }
  },
  "opusSummary": {
    "total_candidates": 12,
    "accepted": 5,
    "rejected": 3,
    "deferred": 4,
    "floor_overrides": 2,
    "keep_fraction_target": 0.4,
    "keep_fraction_actual": 0.417,
    "effective_token_multiplier": 2.4
  },
  "docLossSummary": {
    "doc_0016": 11.518407,
    "doc_0015": 11.517769,
    "doc_0018": 11.519267,
    "doc_0019": 11.516045,
    "doc_0009": 11.515422,
    "doc_0017": 11.514818,
    "doc_0023": 11.516086,
    "doc_0010": 11.513727,
    "doc_0020": 11.520522,
    "doc_0012": 11.514878,
    "doc_0011": 11.51759,
    "doc_0014": 11.517296,
    "doc_0022": 11.5174,
    "doc_0021": 11.51948,
    "doc_0013": 11.514579,
    "doc_0008": 11.513885
  },
  "tokenizer": {
    "model_name": "cl100k_base",
    "tokenizer_sha": "tok_27b6a09dd8613291",
    "vocab_size": 100277,
    "eos_token_string": "EOT",
    "agentic_mask_spans": [
      "[OBSERVATION]",
      "[/OBSERVATION]"
    ],
    "normalizer_id": "unicode_nfc",
    "special_tokens": {
      "pad": "<pad>",
      "eos": "<eos>",
      "bos": "<bos>"
    }
  },
  "manifestSummary": {
    "total": 27,
    "admitted": 24,
    "blocked": 3,
    "eval_shards": [
      "shard_ca51f610fcf6",
      "shard_f8dea85b952b",
      "shard_8f703fea119c"
    ],
    "tokenizer_sha": "tok_27b6a09dd8613291"
  },
  "curriculumStages": [
    {
      "id": "stage_1_general",
      "name": "Seed / General",
      "budget": "70%",
      "weights": {
        "web": 0.49,
        "code": 0.18,
        "indic": 0.16,
        "agentic": 0.02,
        "reasoning": 0.06,
        "stem": 0.09
      }
    },
    {
      "id": "stage_2_reasoning",
      "name": "Reasoning / Code",
      "budget": "20%",
      "weights": {
        "web": 0.25,
        "code": 0.28,
        "indic": 0.14,
        "agentic": 0.03,
        "reasoning": 0.18,
        "stem": 0.12
      }
    },
    {
      "id": "stage_3_anneal",
      "name": "Anneal (Low-LR Cooldown)",
      "budget": "10%",
      "weights": {
        "web": 0.08,
        "code": 0.2,
        "indic": 0.28,
        "agentic": 0.08,
        "reasoning": 0.18,
        "stem": 0.1,
        "long_context": 0.08
      }
    }
  ]
};
