// data.js -- Generated by generate_webapp_data.py from real pipeline output
// (data/wikipedia_stats.json, data/sangraha_stats.json, data/c4_crawl_stats.json)
// Wikipedia: 100,000 articles | Sangraha: 20,000 Indic docs | C4 en.noclean: 20,000 web pages
// Do not hand-edit -- re-run run_pipeline.py then this script instead.

window.PIPELINE_DATA = {
  "wikipedia": {
    "meta": {
      "source": "wikimedia/wikipedia",
      "config": "20231101.en",
      "license": "CC-BY-SA 4.0",
      "description": "English Wikipedia streamed from Hugging Face",
      "initial_docs": 100000,
      "initial_tokens": 96406415,
      "admitted_docs": 95404,
      "admitted_tokens": 93451066,
      "survival_pct": 95.4,
      "total_time_s": 876.8
    },
    "stages": [
      {
        "id": 1,
        "name": "Extract",
        "icon": "🔍",
        "color": "#6366f1",
        "input": 100000,
        "output": 99088,
        "dropped": 912,
        "drop_pct": 0.91,
        "survival": 99.1,
        "input_tok": 96406415,
        "output_tok": 96137890,
        "drop_summary": "912 dropped — 908 stub too short, 4 empty after extraction",
        "what_removed": "Markup/boilerplate remnants (templates, links, nav fragments), reference markers, residual HTML tags",
        "metadata_added": [
          "orig_len",
          "extracted_len",
          "extraction_removed_pct"
        ],
        "processing_time_s": 15.46,
        "example": {
          "before": "In mathematics and computer science, an algorithm () is a finite sequence of rigorous instructions, typically used to solve a class of specific problems or to perform a computation. Algorithms are used as specifications for performing calculations and data processing. More advanced algorithms can us",
          "after": "In mathematics and computer science, an algorithm () is a finite sequence of rigorous instructions, typically used to solve a class of specific problems or to perform a computation. Algorithms are used as specifications for performing calculations and data processing. More advanced algorithms can us",
          "note": "Removed 32.0% markup/boilerplate"
        }
      },
      {
        "id": 2,
        "name": "Normalize",
        "icon": "✨",
        "color": "#8b5cf6",
        "input": 99088,
        "output": 99088,
        "dropped": 0,
        "drop_pct": 0.0,
        "survival": 100.0,
        "input_tok": 96137890,
        "output_tok": 96137837,
        "drop_summary": "No docs dropped",
        "what_removed": "HTML entities, BOM/ZWSP/BIDI overrides and other invisible noise characters, ghost chat-format tags. ZWNJ/ZWJ preserved for Brahmic scripts.",
        "metadata_added": [
          "html_entities_removed",
          "noise_chars_removed",
          "ghost_tags_removed",
          "norm_len"
        ],
        "processing_time_s": 40.36,
        "example": {
          "before": "Alexander is a male given name of Greek origin. The most prominent bearer of the name is Alexander the Great, the king of the Ancient Greek kingdom of Macedonia who created one of the largest empires in ancient history.\n\nVariants listed here are Aleksandar, Aleksander and Aleksandr. Related names an",
          "after": "Alexander is a male given name of Greek origin. The most prominent bearer of the name is Alexander the Great, the king of the Ancient Greek kingdom of Macedonia who created one of the largest empires in ancient history.\n\nVariants listed here are Aleksandar, Aleksander and Aleksandr. Related names an",
          "note": "Entities: 0, Noise chars: 1, Ghost tags: 0"
        }
      },
      {
        "id": 3,
        "name": "Language ID",
        "icon": "🌐",
        "color": "#06b6d4",
        "input": 99088,
        "output": 98335,
        "dropped": 753,
        "drop_pct": 0.76,
        "survival": 99.2,
        "input_tok": 96137837,
        "output_tok": 95817219,
        "drop_summary": "753 dropped — 744 low confidence detection, 3 wrong lang fr, 1 wrong lang it",
        "what_removed": "Wrong-language and low language-detection-confidence documents (validated at runtime, not trusted from directory paths)",
        "metadata_added": [
          "detected_lang",
          "lang_confidence",
          "script_coverage_pct"
        ],
        "processing_time_s": 20.59,
        "example": {
          "before": "A\n\nJohn Adair\nB. R. Ambedkar\nGiulio Angioni\nJon Altman\nArjun Appadurai\nTalal Asad\nTimothy Asch\nScott Atran\nMarc Augé\n\nB\n\nNigel Barley\nFredrik Barth\nVasily Bartold\nKeith H. Basso\nDaisy Bates\nGregory Ba",
          "after": "[QUARANTINED]",
          "note": "Low detection confidence: en at 0.35"
        }
      },
      {
        "id": 4,
        "name": "Quality Filter",
        "icon": "🧹",
        "color": "#10b981",
        "input": 98335,
        "output": 95652,
        "dropped": 2683,
        "drop_pct": 2.73,
        "survival": 97.3,
        "input_tok": 95817219,
        "output_tok": 94477347,
        "drop_summary": "2,683 dropped — 1,847 avg line len too short, 508 punct end ratio low, 307 symbol ratio too high",
        "what_removed": "Documents failing 2+ Gopher/C4 heuristic rules (word length, symbol ratio, line length, punctuation-end, stopword density, duplicate lines) or low educational score",
        "metadata_added": [
          "quality_flags",
          "avg_word_len",
          "symbol_ratio",
          "punct_end_ratio",
          "stopword_density",
          "dup_line_ratio",
          "edu_score"
        ],
        "processing_time_s": 47.28,
        "example": {
          "before": "The Academy Award for Best Production Design recognizes achievement for art direction in film. The category's original name was Best Art Direction, but was changed to its current name in 2012 for the 85th Academy Awards. This change resulted from the Art Directors' branch of the Academy of Motion Pi",
          "after": "[DROPPED]",
          "note": "Failed heuristics: ['avg_line_len_too_short_22', 'punct_end_ratio_low_0.02']"
        }
      },
      {
        "id": 5,
        "name": "Deduplicate",
        "icon": "🔁",
        "color": "#f59e0b",
        "input": 95652,
        "output": 95575,
        "dropped": 77,
        "drop_pct": 0.08,
        "survival": 99.9,
        "input_tok": 94477347,
        "output_tok": 94464088,
        "drop_summary": "77 dropped — 77 near duplicate minhash",
        "what_removed": "Exact duplicates (SHA-256) and near-duplicates (MinHash LSH, Jaccard >= 0.80)",
        "metadata_added": [
          "content_hash",
          "is_near_dup",
          "dup_of"
        ],
        "processing_time_s": 648.95,
        "example": {
          "before": "Cunningham Open is a former electoral division of Fiji, one of 25 open constituencies that were elected by universal suffrage (the remaining 46 seats, called communal constituencies, were allocated by",
          "after": "[NEAR-DUPLICATE REMOVED]",
          "note": "Jaccard >= 0.8 with an earlier document"
        }
      },
      {
        "id": 6,
        "name": "PII Scrub",
        "icon": "🔒",
        "color": "#ef4444",
        "input": 95575,
        "output": 95575,
        "dropped": 0,
        "drop_pct": 0.0,
        "survival": 100.0,
        "input_tok": 94464088,
        "output_tok": 94462470,
        "drop_summary": "No docs dropped",
        "what_removed": "Emails, IPv4 addresses, phone numbers, AADHAAR and PAN numbers — replaced with typed placeholders, not empty strings",
        "metadata_added": [
          "pii_redactions",
          "pii_types_found"
        ],
        "processing_time_s": 63.26,
        "example": {
          "before": "Abraham Lincoln ( ; February 12, 1809 – April 15, 1865) was an American lawyer, politician, and statesman who served as the 16th president of the United States from 1861 until his assassination in 1865. Lincoln led the Union through the American Civil War to defend the nation as a constitutional uni",
          "after": "Abraham Lincoln ( ; February 12, 1809 – April 15, 1865) was an American lawyer, politician, and statesman who served as the 16th president of the United States from 1861 until his assassination in 1865. Lincoln led the Union through the American Civil War to defend the nation as a constitutional uni",
          "note": "PII found: {'phone_intl': 1}"
        }
      },
      {
        "id": 7,
        "name": "Decontaminate",
        "icon": "🛡",
        "color": "#f97316",
        "input": 95575,
        "output": 95404,
        "dropped": 171,
        "drop_pct": 0.18,
        "survival": 99.8,
        "input_tok": 94462470,
        "output_tok": 93451066,
        "drop_summary": "171 dropped — 100 contamination benchmark pattern: how many.*t, 44 contamination benchmark pattern: \\.*\\(b\\, 8 contamination mcq format detected (4 options",
        "what_removed": "Documents overlapping benchmark n-grams or matching MCQ/Q&A patterns (decontamination firewall)",
        "metadata_added": [
          "decontam_status",
          "contam_reason"
        ],
        "processing_time_s": 32.47,
        "example": {
          "before": "Apple Inc. is an American multinational technology company headquartered in Cupertino, California. , Apple is the world's biggest company by market capitalization, and with the largest technology company by 2022 revenue. , Apple is the fourth-largest personal computer vendor by unit sales; the large",
          "after": "[QUARANTINED - BENCHMARK OVERLAP]",
          "note": "Contamination reason: benchmark_pattern: how many.*total"
        }
      },
      {
        "id": 8,
        "name": "Manifest",
        "icon": "📋",
        "color": "#64748b",
        "input": 95404,
        "output": 95404,
        "dropped": 0,
        "drop_pct": 0.0,
        "survival": 100.0,
        "input_tok": 93451066,
        "output_tok": 93451066,
        "drop_summary": "No docs dropped",
        "what_removed": "Nothing dropped — stamps SHA-256 shard_id, license, token count and provenance on every admitted document",
        "metadata_added": [
          "manifest"
        ],
        "processing_time_s": 8.4,
        "example": {
          "before": "(no example captured)",
          "after": "",
          "note": ""
        }
      }
    ]
  },
  "sangraha": {
    "meta": {
      "source": "ai4bharat/sangraha",
      "config": "verified / hin + tel",
      "license": "CC-BY 4.0",
      "description": "Indic dataset (Hindi + Telugu) — real web + PDF-extracted text demonstrating the Sovereign Indic Exception",
      "initial_docs": 20000,
      "initial_tokens": 8744920,
      "admitted_docs": 18483,
      "admitted_tokens": 8084438,
      "survival_pct": 92.4,
      "total_time_s": 90.5,
      "dedup_note": "Global dedup removed 185 duplicates (0.99%) from real ai4bharat/sangraha web + PDF-extracted text. Real Indic web crawls have heavy news syndication — the same article appears across many regional sites, which is why global dedup is load-bearing."
    },
    "stages": [
      {
        "id": 1,
        "name": "Extract",
        "icon": "🔍",
        "color": "#6366f1",
        "input": 20000,
        "output": 19995,
        "dropped": 5,
        "drop_pct": 0.03,
        "survival": 100.0,
        "input_tok": 8744920,
        "output_tok": 8742531,
        "drop_summary": "5 dropped — 5 stub too short",
        "what_removed": "Markup/boilerplate remnants (templates, links, nav fragments), reference markers, residual HTML tags",
        "metadata_added": [
          "orig_len",
          "extracted_len",
          "extraction_removed_pct"
        ],
        "processing_time_s": 1.64,
        "example": {
          "before": "गाँव का रामू - क्या हाल है रानी ?\n लड़की - कौन बद्तमीज़ बोल रहा है ?\n रामू - क्या री ? अपने आशिक को नहीं पहचानती ,,\nलड़की (गुस्से में)- मेरा नम्बर कहाँ से मिला ?\n लाजो का गोलू रोज ऑफिस से लेट आता था,\nमें किसी और से चक्कर है,\nनौकरानी - नहीं , ऐसा नहीं हो सकता,\nलाजो - क्यों ?\n .\n .\n .\n .\n .\n .\n .\n .\n ",
          "after": "गाँव का रामू - क्या हाल है रानी ?\n लड़की - कौन बद्तमीज़ बोल रहा है ?\n रामू - क्या री ? अपने आशिक को नहीं पहचानती ,,\nलड़की (गुस्से में)- मेरा नम्बर कहाँ से मिला ?\n लाजो का गोलू रोज ऑफिस से लेट आता था,\nमें किसी और से चक्कर है,\nनौकरानी - नहीं , ऐसा नहीं हो सकता,\nलाजो - क्यों ?\n गोलू की गर्लफ्रेंड उसे क",
          "note": "Removed 5.4% markup/boilerplate"
        }
      },
      {
        "id": 2,
        "name": "Normalize",
        "icon": "✨",
        "color": "#8b5cf6",
        "input": 19995,
        "output": 19995,
        "dropped": 0,
        "drop_pct": 0.0,
        "survival": 100.0,
        "input_tok": 8742531,
        "output_tok": 8742525,
        "drop_summary": "No docs dropped",
        "what_removed": "HTML entities, BOM/ZWSP/BIDI overrides and other invisible noise characters, ghost chat-format tags. ZWNJ/ZWJ preserved for Brahmic scripts.",
        "metadata_added": [
          "html_entities_removed",
          "noise_chars_removed",
          "ghost_tags_removed",
          "norm_len"
        ],
        "processing_time_s": 4.55,
        "example": {
          "before": "दो करोड़ नब्बे लाख बहत्तर हज़ार बीस संध्या एक हज़ार नौ सौ बजे मुख्य समाचार एक केन्द्र सरकार ने नई शिक्षा नीति को स्वीकृति प्रदान की दो हजार पैंतीस तक उच्च शिक्षा के क्षेत्र में सकल नामांकन दर पचास प्रतिशत तक पहुंचाना लक्ष्य\nराज्य में कोरोना संक्रमितों की संख्या दस हजार के करीब पहुंची लगभग चार हजार म",
          "after": "दो करोड़ नब्बे लाख बहत्तर हज़ार बीस संध्या एक हज़ार नौ सौ बजे मुख्य समाचार एक केन्द्र सरकार ने नई शिक्षा नीति को स्वीकृति प्रदान की दो हजार पैंतीस तक उच्च शिक्षा के क्षेत्र में सकल नामांकन दर पचास प्रतिशत तक पहुंचाना लक्ष्य\nराज्य में कोरोना संक्रमितों की संख्या दस हजार के करीब पहुंची लगभग चार हजार म",
          "note": "Entities: 0, Noise chars: 1, Ghost tags: 0"
        }
      },
      {
        "id": 3,
        "name": "Language ID",
        "icon": "🌐",
        "color": "#06b6d4",
        "input": 19995,
        "output": 19948,
        "dropped": 47,
        "drop_pct": 0.24,
        "survival": 99.8,
        "input_tok": 8742525,
        "output_tok": 8709344,
        "drop_summary": "47 dropped — 44 low confidence detection, 2 unexpected lang mg, 1 unexpected lang pt",
        "what_removed": "Wrong-language and low language-detection-confidence documents (validated at runtime, not trusted from directory paths)",
        "metadata_added": [
          "detected_lang",
          "lang_confidence",
          "script_coverage_pct"
        ],
        "processing_time_s": 7.74,
        "example": {
          "before": "वग्गणाहिं च केवडियं खेत्तं फोसिढं ? लोगस्स असंखेज्जदिभागो सव्वलोगो वा । असं खेज्जपदसियदव्ववग्गण पहुडि जाव सुहुमणिगोदवग्गणे त्ति ताव एदासिं वग्गणाणमेगसेडीहि केवडियं खेत्तं फोसिदं ? अदीदवमाणेण सव्वलोगो ",
          "after": "[QUARANTINED]",
          "note": "Low detection confidence: hi at 0.33"
        }
      },
      {
        "id": 4,
        "name": "Quality Filter",
        "icon": "🧹",
        "color": "#10b981",
        "input": 19948,
        "output": 18671,
        "dropped": 1277,
        "drop_pct": 6.4,
        "survival": 93.6,
        "input_tok": 8709344,
        "output_tok": 8164456,
        "drop_summary": "1,277 dropped — 610 avg line len too long, 593 punct end ratio low, 56 symbol ratio too high",
        "what_removed": "Documents failing 2+ Gopher/C4 heuristic rules (word length, symbol ratio, line length, punctuation-end, stopword density, duplicate lines) or low educational score",
        "metadata_added": [
          "quality_flags",
          "avg_word_len",
          "symbol_ratio",
          "punct_end_ratio",
          "stopword_density",
          "dup_line_ratio",
          "edu_score"
        ],
        "processing_time_s": 5.43,
        "example": {
          "before": "गाँव का रामू - क्या हाल है रानी ?\n लड़की - कौन बद्तमीज़ बोल रहा है ?\n रामू - क्या री ? अपने आशिक को नहीं पहचानती ,,\nलड़की (गुस्से में)- मेरा नम्बर कहाँ से मिला ?\n लाजो का गोलू रोज ऑफिस से लेट आता था,\nमें किसी और से चक्कर है,\nनौकरानी - नहीं , ऐसा नहीं हो सकता,\nलाजो - क्यों ?\n गोलू की गर्लफ्रेंड उसे क",
          "after": "[DROPPED]",
          "note": "Failed heuristics: ['avg_line_len_too_short_29', 'punct_end_ratio_low_0.23']"
        }
      },
      {
        "id": 5,
        "name": "Deduplicate",
        "icon": "🔁",
        "color": "#f59e0b",
        "input": 18671,
        "output": 18486,
        "dropped": 185,
        "drop_pct": 0.99,
        "survival": 99.0,
        "input_tok": 8164456,
        "output_tok": 8087765,
        "drop_summary": "185 dropped — 175 exact duplicate, 10 near duplicate minhash",
        "what_removed": "Exact duplicates (SHA-256) and near-duplicates (MinHash LSH, Jaccard >= 0.80)",
        "metadata_added": [
          "content_hash",
          "is_near_dup",
          "dup_of"
        ],
        "processing_time_s": 59.54,
        "example": {
          "before": "।ग्राम क्रमांक :\n।ग्राम का नाम :\n।तहसील :\n।जनपद :\n।फसली वर्ष :\n।भाग :\n।प्रत्येक गाटे का क्षेत्रफल (हे.)\n।1 - ऐसी भूमि, जिसमें सरकार अथवा गाँवसभा या अन्य स्थानीय अधिकारिकी जिसे1950 ई. के उ. प्र. ज. वि.",
          "after": "[NEAR-DUPLICATE REMOVED]",
          "note": "Jaccard >= 0.8 with an earlier document"
        }
      },
      {
        "id": 6,
        "name": "PII Scrub",
        "icon": "🔒",
        "color": "#ef4444",
        "input": 18486,
        "output": 18486,
        "dropped": 0,
        "drop_pct": 0.0,
        "survival": 100.0,
        "input_tok": 8087765,
        "output_tok": 8087686,
        "drop_summary": "No docs dropped",
        "what_removed": "Emails, IPv4 addresses, phone numbers, AADHAAR and PAN numbers — replaced with typed placeholders, not empty strings",
        "metadata_added": [
          "pii_redactions",
          "pii_types_found"
        ],
        "processing_time_s": 7.18,
        "example": {
          "before": "राष्ट्रीय अग्निशमन सेवा सप्ताह के अंतर्गत ऊना में 20 अप्रैल तक आमजन को आग के प्रति जागरूक करने के लिए विशेष अभियान चलाया जा रहा है। 14 अप्रैल से शुरू हुए इस कार्यक्रम के उपलक्ष्य में बुधवार को अग्निशमन केंद्र ऊना के कर्मचारियों ने दो मिनट का मौन रखकर अग्निशमन महकमें में शहीद हुए जवानों को श्रद्धांजल",
          "after": "राष्ट्रीय अग्निशमन सेवा सप्ताह के अंतर्गत ऊना में 20 अप्रैल तक आमजन को आग के प्रति जागरूक करने के लिए विशेष अभियान चलाया जा रहा है। 14 अप्रैल से शुरू हुए इस कार्यक्रम के उपलक्ष्य में बुधवार को अग्निशमन केंद्र ऊना के कर्मचारियों ने दो मिनट का मौन रखकर अग्निशमन महकमें में शहीद हुए जवानों को श्रद्धांजल",
          "note": "PII found: {'phone_intl': 1}"
        }
      },
      {
        "id": 7,
        "name": "Decontaminate",
        "icon": "🛡",
        "color": "#f97316",
        "input": 18486,
        "output": 18483,
        "dropped": 3,
        "drop_pct": 0.02,
        "survival": 100.0,
        "input_tok": 8087686,
        "output_tok": 8084438,
        "drop_summary": "3 dropped — 2 contamination benchmark pattern: \\.*\\(b\\, 1 contamination mcq format detected (4 options",
        "what_removed": "Documents overlapping benchmark n-grams or matching MCQ/Q&A patterns (decontamination firewall)",
        "metadata_added": [
          "decontam_status",
          "contam_reason"
        ],
        "processing_time_s": 2.65,
        "example": {
          "before": "स्त्रियों में से 20 प्रतिशत भौरतों में घबराहट पैदा होने लगती है और उनके चेहरे पर मुंहासे निकल प्राते हैं तथा उनमें मोटापा श्रा जाता है;\n( ख ) क्या इस सम्बन्ध में पेरिस के दो वैज्ञानिकों, डा० फिकाइस मिटक्लाने तथा डा० जार्ज मेलकी की रिपोर्टों की धार सरकार का ध्यान दिलाया गया है; और\n(ग) यदि हां, तो इस ",
          "after": "[QUARANTINED - BENCHMARK OVERLAP]",
          "note": "Contamination reason: benchmark_pattern: \\(a\\).*\\(b\\).*\\(c\\).*\\(d\\)"
        }
      },
      {
        "id": 8,
        "name": "Manifest",
        "icon": "📋",
        "color": "#64748b",
        "input": 18483,
        "output": 18483,
        "dropped": 0,
        "drop_pct": 0.0,
        "survival": 100.0,
        "input_tok": 8084438,
        "output_tok": 8084438,
        "drop_summary": "No docs dropped",
        "what_removed": "Nothing dropped — stamps SHA-256 shard_id, license, token count and provenance on every admitted document",
        "metadata_added": [
          "manifest"
        ],
        "processing_time_s": 1.76,
        "example": {
          "before": "(no example captured)",
          "after": "",
          "note": ""
        }
      }
    ]
  },
  "c4_crawl": {
    "meta": {
      "source": "allenai/c4",
      "config": "en.noclean",
      "license": "ODC-BY",
      "description": "allenai/c4 en.noclean — unfiltered CommonCrawl pages. No quality filtering by source. Contains nav boilerplate, SEO spam, multilingual noise, short stubs.",
      "initial_docs": 20000,
      "initial_tokens": 24494758,
      "admitted_docs": 6814,
      "admitted_tokens": 9227034,
      "survival_pct": 34.1,
      "total_time_s": 103.4
    },
    "stages": [
      {
        "id": 1,
        "name": "Extract",
        "icon": "🔍",
        "color": "#6366f1",
        "input": 20000,
        "output": 19456,
        "dropped": 544,
        "drop_pct": 2.72,
        "survival": 97.3,
        "input_tok": 24494758,
        "output_tok": 23691479,
        "drop_summary": "544 dropped — 544 stub too short",
        "what_removed": "Markup/boilerplate remnants (templates, links, nav fragments), reference markers, residual HTML tags",
        "metadata_added": [
          "orig_len",
          "extracted_len",
          "extraction_removed_pct"
        ],
        "processing_time_s": 4.5,
        "example": {
          "before": "Kitchen Thermometers - Kitchen - Shop\nFree Ground Shipping on orders over $25\nTaylor\nLog In\nMy Cart\nCheckout\nFacebook\nTwitter\nSearch\nToggle navigation\nShop\nKitchen\nBath\nWeather\nGrill Tools\nReplacement Parts\nSupport\nApp Partners\nCustomer Service\nAbout Us\nLog In\nMy Cart\nCheckout\nFacebook\nTwitter\nSearc",
          "after": "Kitchen Thermometers - Kitchen - Shop\nFree Ground Shipping on orders over $25\nTaylor\nLog In\nMy Cart\nCheckout\nFacebook\nTwitter\nSearch\nToggle navigation\nShop\nKitchen\nBath\nWeather\nGrill Tools\nReplacement Parts\nSupport\nApp Partners\nCustomer Service\nAbout Us\nLog In\nMy Cart\nCheckout\nFacebook\nTwitter\nSearc",
          "note": "Removed 7.1% markup/boilerplate"
        }
      },
      {
        "id": 2,
        "name": "Normalize",
        "icon": "✨",
        "color": "#8b5cf6",
        "input": 19456,
        "output": 19456,
        "dropped": 0,
        "drop_pct": 0.0,
        "survival": 100.0,
        "input_tok": 23691479,
        "output_tok": 23689850,
        "drop_summary": "No docs dropped",
        "what_removed": "HTML entities, BOM/ZWSP/BIDI overrides and other invisible noise characters, ghost chat-format tags. ZWNJ/ZWJ preserved for Brahmic scripts.",
        "metadata_added": [
          "html_entities_removed",
          "noise_chars_removed",
          "ghost_tags_removed",
          "norm_len"
        ],
        "processing_time_s": 11.26,
        "example": {
          "before": "Slot Seeding with New Holland TM150. | Gasilski Dom Nova Gorica Poker\nGasilski Dom Nova Gorica Poker - Slot Seeding with New Holland TM150.\n++NEW Coyote Queen slot machine, DBG\nHere is another Aristocrat game designed for players that like razzle dazzle and also progressives. I'm not a big fan of th",
          "after": "Slot Seeding with New Holland TM150. | Gasilski Dom Nova Gorica Poker\nGasilski Dom Nova Gorica Poker - Slot Seeding with New Holland TM150.\n++NEW Coyote Queen slot machine, DBG\nHere is another Aristocrat game designed for players that like razzle dazzle and also progressives. I'm not a big fan of th",
          "note": "Entities: 0, Noise chars: 6, Ghost tags: 0"
        }
      },
      {
        "id": 3,
        "name": "Language ID",
        "icon": "🌐",
        "color": "#06b6d4",
        "input": 19456,
        "output": 12172,
        "dropped": 7284,
        "drop_pct": 37.44,
        "survival": 62.6,
        "input_tok": 23689850,
        "output_tok": 14903264,
        "drop_summary": "7,284 dropped — 7,191 low confidence detection, 27 wrong lang zh, 9 wrong lang fr",
        "what_removed": "Wrong-language and low language-detection-confidence documents (validated at runtime, not trusted from directory paths)",
        "metadata_added": [
          "detected_lang",
          "lang_confidence",
          "script_coverage_pct"
        ],
        "processing_time_s": 4.56,
        "example": {
          "before": "Download Link page 2\nTCV Menu\nHome\nGeneral\nSecurity\nWordpress Template\nWordpress Plugin\nVideo\nTutorial\nDereferer\nYYEN.INFO This tool will help you turn a long and complicated link into a short one. Sh",
          "after": "[QUARANTINED]",
          "note": "Low detection confidence: en at 0.58"
        }
      },
      {
        "id": 4,
        "name": "Quality Filter",
        "icon": "🧹",
        "color": "#10b981",
        "input": 12172,
        "output": 6931,
        "dropped": 5241,
        "drop_pct": 43.06,
        "survival": 56.9,
        "input_tok": 14903264,
        "output_tok": 9662442,
        "drop_summary": "5,241 dropped — 4,160 avg line len too short, 778 punct end ratio low, 247 symbol ratio too high",
        "what_removed": "Documents failing 2+ Gopher/C4 heuristic rules (word length, symbol ratio, line length, punctuation-end, stopword density, duplicate lines) or low educational score",
        "metadata_added": [
          "quality_flags",
          "avg_word_len",
          "symbol_ratio",
          "punct_end_ratio",
          "stopword_density",
          "dup_line_ratio",
          "edu_score"
        ],
        "processing_time_s": 6.41,
        "example": {
          "before": "November 24, 2016 – World News, Breaking News\nWednesday, April 24, 2019\nLatest:\nFitbit introduced “smart” watches, Versa Lite, and a fitness bracelets under $100\nUpgraded Acer laptop Aspire 3 entered the Ukrainian market with a price tag from 8939 UAH\nMicrosoft discontinues support fitness bracelets",
          "after": "[DROPPED]",
          "note": "Failed heuristics: ['punct_end_ratio_low_0.03', 'dup_lines_ratio_high_0.44']"
        }
      },
      {
        "id": 5,
        "name": "Deduplicate",
        "icon": "🔁",
        "color": "#f59e0b",
        "input": 6931,
        "output": 6872,
        "dropped": 59,
        "drop_pct": 0.85,
        "survival": 99.2,
        "input_tok": 9662442,
        "output_tok": 9636720,
        "drop_summary": "59 dropped — 35 near duplicate minhash, 24 exact duplicate",
        "what_removed": "Exact duplicates (SHA-256) and near-duplicates (MinHash LSH, Jaccard >= 0.80)",
        "metadata_added": [
          "content_hash",
          "is_near_dup",
          "dup_of"
        ],
        "processing_time_s": 65.4,
        "example": {
          "before": "Plan cul cougar instacougar rencontre femme mure\nXML Sitemap\nThis is a XML Sitemap which is supposed to be processed by search engines which follow the XML Sitemap standard like Ask.com, Bing, Google ",
          "after": "[NEAR-DUPLICATE REMOVED]",
          "note": "Jaccard >= 0.8 with an earlier document"
        }
      },
      {
        "id": 6,
        "name": "PII Scrub",
        "icon": "🔒",
        "color": "#ef4444",
        "input": 6872,
        "output": 6872,
        "dropped": 0,
        "drop_pct": 0.0,
        "survival": 100.0,
        "input_tok": 9636720,
        "output_tok": 9628366,
        "drop_summary": "No docs dropped",
        "what_removed": "Emails, IPv4 addresses, phone numbers, AADHAAR and PAN numbers — replaced with typed placeholders, not empty strings",
        "metadata_added": [
          "pii_redactions",
          "pii_types_found"
        ],
        "processing_time_s": 7.28,
        "example": {
          "before": "Slot Seeding with New Holland TM150. | Gasilski Dom Nova Gorica Poker\nGasilski Dom Nova Gorica Poker - Slot Seeding with New Holland TM150.\n++NEW Coyote Queen slot machine, DBG\nHere is another Aristocrat game designed for players that like razzle dazzle and also progressives. I'm not a big fan of th",
          "after": "Slot Seeding with New Holland TM150. | Gasilski Dom Nova Gorica Poker\nGasilski Dom Nova Gorica Poker - Slot Seeding with New Holland TM150.\n++NEW Coyote Queen slot machine, DBG\nHere is another Aristocrat game designed for players that like razzle dazzle and also progressives. I'm not a big fan of th",
          "note": "PII found: {'email': 17, 'phone_intl': 3}"
        }
      },
      {
        "id": 7,
        "name": "Decontaminate",
        "icon": "🛡",
        "color": "#f97316",
        "input": 6872,
        "output": 6814,
        "dropped": 58,
        "drop_pct": 0.84,
        "survival": 99.2,
        "input_tok": 9628366,
        "output_tok": 9227034,
        "drop_summary": "58 dropped — 39 contamination benchmark pattern: how many.*t, 11 contamination benchmark pattern: \\.*\\(b\\, 4 contamination benchmark pattern: which of th",
        "what_removed": "Documents overlapping benchmark n-grams or matching MCQ/Q&A patterns (decontamination firewall)",
        "metadata_added": [
          "decontam_status",
          "contam_reason"
        ],
        "processing_time_s": 3.23,
        "example": {
          "before": "Cyrsti's Condo: The Right or Wrong Person for the Job?\nCyrsti's Condo\nYour Transgender Girl in the Neighborhood-JJ'S HOUSE!\nTuesday, August 25, 2015\nThe Right or Wrong Person for the Job?\nI really don't know how many times I have sworn myself off the \"allure\" or lack of it from Caitlin Jenner.\nKrist",
          "after": "[QUARANTINED - BENCHMARK OVERLAP]",
          "note": "Contamination reason: benchmark_pattern: how many.*total"
        }
      },
      {
        "id": 8,
        "name": "Manifest",
        "icon": "📋",
        "color": "#64748b",
        "input": 6814,
        "output": 6814,
        "dropped": 0,
        "drop_pct": 0.0,
        "survival": 100.0,
        "input_tok": 9227034,
        "output_tok": 9227034,
        "drop_summary": "No docs dropped",
        "what_removed": "Nothing dropped — stamps SHA-256 shard_id, license, token count and provenance on every admitted document",
        "metadata_added": [
          "manifest"
        ],
        "processing_time_s": 0.77,
        "example": {
          "before": "(no example captured)",
          "after": "",
          "note": ""
        }
      }
    ]
  },
  "strategies": [
    {
      "id": 1,
      "name": "Extraction",
      "icon": "🔍",
      "color": "#6366f1",
      "gap": "Earlier approach kept nav links and cookie banners as document body content",
      "fix": "trafilatura on raw WARC; strip {{templates}}, [[links]], ==Sections==, [refs]",
      "drop": "Stubs <150 chars, empty after markup strip"
    },
    {
      "id": 2,
      "name": "Normalization",
      "icon": "✨",
      "color": "#8b5cf6",
      "gap": "No shared clean_text() normalization function — garbage tokens baked into tokenizer",
      "fix": "NFC Unicode → HTML unescape → strip BOM/ZWSP/BIDI → PRESERVE ZWNJ/ZWJ → collapse whitespace",
      "drop": "Docs <100 chars after normalization"
    },
    {
      "id": 3,
      "name": "Language ID",
      "icon": "🌐",
      "color": "#06b6d4",
      "gap": "Trusted directory naming (verified/asm/) without runtime validation; Python dict misrouting bug",
      "fix": "fastText detection on every doc + script-histogram validation (Unicode codepoint block coverage)",
      "drop": "Confidence <0.70, wrong-language docs, <30% expected script coverage"
    },
    {
      "id": 4,
      "name": "Quality Filter",
      "icon": "🧹",
      "color": "#10b981",
      "gap": "English-heavy proxy classifier penalised Indic scripts; bad noise admitted via always-on bypass",
      "fix": "6 Gopher/C4 heuristic rules (word-len, symbol-ratio, line-len, punct-end, stopword, dup-lines) + FineWeb-Edu edu score; Indic-aware thresholds",
      "drop": "2+ heuristic failures or low edu_score"
    },
    {
      "id": 5,
      "name": "Deduplication",
      "icon": "🔁",
      "color": "#f59e0b",
      "gap": "Only local per-source dedup — cross-shard duplicates leaked, wasting compute",
      "fix": "Pass 1: SHA-256 exact hash. Pass 2: MinHash LSH (128 perms, shingle k=5, Jaccard ≥0.80)",
      "drop": "Exact SHA-256 matches, near-dups with Jaccard ≥0.80"
    },
    {
      "id": 6,
      "name": "PII Scrub",
      "icon": "🔒",
      "color": "#ef4444",
      "gap": "Lacked PII scrubbing for Indic pipelines — personal identifiers exposed in training set",
      "fix": "Regex: email, IPv4, phone, AADHAAR, PAN. Typed placeholder [EMAIL_REDACTED] not empty string",
      "drop": "Docs <50 chars after scrubbing (rare)"
    },
    {
      "id": 7,
      "name": "Decontamination",
      "icon": "🛡",
      "color": "#f97316",
      "gap": "No active decontamination firewall — 18.7% benchmark collision rate discovered post-training",
      "fix": "n-gram fingerprint (n=8) + MCQ pattern scan against MMLU/GSM8K/HumanEval. 3-tier firewall.",
      "drop": "Benchmark overlap or MCQ format detected"
    },
    {
      "id": 8,
      "name": "Manifest",
      "icon": "📋",
      "color": "#64748b",
      "gap": "Non-deterministic row counters for shard IDs; words×1.3 token estimate → 10× undercount for Indic",
      "fix": "shard_id = sha256[:12] (content-addressed). Token counting made consistent end-to-end.",
      "drop": "None — stamps provenance on all admitted docs"
    },
    {
      "id": 9,
      "name": "Ghost-Tag Trap",
      "icon": "👻",
      "color": "#ec4899",
      "gap": "Chat markers [USER]/[ASSISTANT]/### Instruction: baked as ghost subwords during pretraining → SFT collision",
      "fix": "Rewrite ALL chat-format markers to canonical special tokens at pretraining ingestion",
      "drop": "N/A — rewrite stage"
    }
  ],
  "sampleManifest": {
    "shard_id": "shard_44e2681d9009",
    "source": "wikimedia/wikipedia",
    "source_url": "https://en.wikipedia.org/wiki/Anarchism",
    "license_class": "CC-BY-SA-4.0",
    "contributor_id": "era5-s4-wikipedia",
    "cleaning_script": "run_pipeline.py",
    "cleaning_script_hash": "96cb9fda3534758e35cb0182bb267da79c8a7d7962ed630a177091514289944f",
    "ingest_timestamp": "2026-07-24T16:39:22.027646+00:00",
    "sha256": "44e2681d9009d89d8cda8513dc6389f073872e9c476eccb8f748fc4a3f74e185",
    "token_count": 8725,
    "lang_distribution": {
      "en": 100
    },
    "pipeline_stages_applied": [
      "extraction",
      "normalization",
      "langid",
      "quality_filter",
      "deduplication",
      "pii_scrub",
      "decontamination",
      "manifest"
    ],
    "quality_score": 2.81,
    "pii_redactions": 0,
    "extraction_removed_pct": 0.0,
    "status": "ADMITTED"
  }
};
