/* ============================================================
   SESSION 13 — Reversible LLMs — APP
   Renders window.SESSION_DATA (generated by revllm.export from
   the experiment results) into tables and hand-rolled SVG charts.
   No build step, no libraries; charts follow the theme via CSS vars.
   ============================================================ */

const D = window.SESSION_DATA || { runs: [], curves: {}, tables: {}, heroStats: [], meta: {} };
const $ = (s, r = document) => r.querySelector(s);
const $$ = (s, r = document) => Array.from(r.querySelectorAll(s));
const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const SVGNS = 'http://www.w3.org/2000/svg';

const COLORS = { baseline: '#64748b', midpoint: '#6366f1', euler: '#f59e0b' };
const SCALE_COLORS = { 128: '#f59e0b', 256: '#10b981', 512: '#06b6d4', 1024: '#f43f5e' };
const RUN = Object.fromEntries(D.runs.map(r => [r.label, r]));
const L = { base: 'exp1_baseline_x', mid: 'exp2_midpoint_x', eul: 'exp3_euler_x',
            x2: 'exp4_euler_2x', x4: 'exp5_euler_4x', x8: 'exp6_euler_8x' };
const SHORT = { [L.base]: 'Baseline', [L.mid]: 'Midpoint', [L.eul]: 'Euler', [L.x2]: 'Euler 2x', [L.x4]: 'Euler 4x', [L.x8]: 'Euler 8x' };

const fmt = {
  n: (v, d = 0) => v == null ? 'n/a' : Number(v).toLocaleString(undefined, { minimumFractionDigits: d, maximumFractionDigits: d }),
  pct: (v, d = 1) => v == null ? 'n/a' : (v * 100).toFixed(d) + '%',
  k: (v) => v == null ? 'n/a' : (v / 1000).toFixed(1) + 'k',
};

/* ═══════════════════════ Tooltip ═══════════════════════ */
const tip = $('#chart-tip');
function showTip(evt, html) { tip.innerHTML = html; tip.classList.add('show'); moveTip(evt); }
function moveTip(evt) { tip.style.left = (evt.clientX + 14) + 'px'; tip.style.top = (evt.clientY + 14) + 'px'; }
function hideTip() { tip.classList.remove('show'); }

/* ═══════════════════════ SVG helpers ═══════════════════════ */
function svgEl(tag, attrs = {}, parent) {
  const e = document.createElementNS(SVGNS, tag);
  for (const [k, v] of Object.entries(attrs)) e.setAttribute(k, v);
  if (parent) parent.appendChild(e);
  return e;
}
function text(parent, x, y, str, attrs = {}) {
  const t = svgEl('text', { x, y, ...attrs }, parent);
  t.textContent = str;
  return t;
}
function niceTicks(min, max, count = 5) {
  const span = max - min || 1;
  const step0 = span / count;
  const mag = Math.pow(10, Math.floor(Math.log10(step0)));
  const step = [1, 2, 2.5, 5, 10].map(m => m * mag).find(s => span / s <= count) || 10 * mag;
  const ticks = [];
  for (let v = Math.ceil(min / step) * step; v <= max + 1e-9; v += step) ticks.push(+v.toFixed(10));
  return ticks;
}
function legend(el, items) {
  const div = document.createElement('div');
  div.className = 'chart-legend';
  div.innerHTML = items.map(i => `<span><i style="background:${i.color}"></i>${esc(i.name)}</span>`).join('');
  el.appendChild(div);
}
function hoverDot(g, x, y, color, html, r = 3.5) {
  const c = svgEl('circle', { cx: x, cy: y, r, fill: color, class: 'dot' }, g);
  const hit = svgEl('circle', { cx: x, cy: y, r: 9, fill: 'transparent', style: 'cursor:pointer' }, g);
  hit.addEventListener('mouseenter', e => { c.setAttribute('r', r + 2); showTip(e, html); });
  hit.addEventListener('mousemove', moveTip);
  hit.addEventListener('mouseleave', () => { c.setAttribute('r', r); hideTip(); });
}

/* ═══════════════════════ Line chart ═══════════════════════ */
function lineChart(el, o) {
  el.innerHTML = '';
  const W = Math.max(320, el.clientWidth || o.width || 620), H = o.height || 300, m = { t: 14, r: 18, b: 42, l: 54 };
  const svg = svgEl('svg', { viewBox: `0 0 ${W} ${H}` }, el);
  const all = o.series.flatMap(s => s.x.map((x, i) => [x, s.y[i]])).filter(p => p[1] != null);
  const xs = all.map(p => p[0]), ys = all.map(p => p[1]);
  const tx = o.xLog ? Math.log2 : (v => v);
  let x0 = o.xMin ?? Math.min(...xs), x1 = o.xMax ?? Math.max(...xs);
  let y0 = o.yMin ?? Math.min(...ys), y1 = o.yMax ?? Math.max(...ys);
  if (o.yLog) { y0 = Math.log10(y0); y1 = Math.log10(y1); }
  const ty = o.yLog ? Math.log10 : (v => v);
  const X = v => m.l + (tx(v) - tx(x0)) / (tx(x1) - tx(x0) || 1) * (W - m.l - m.r);
  const Y = v => H - m.b - (ty(v) - y0) / (y1 - y0 || 1) * (H - m.t - m.b);
  const grid = svgEl('g', { class: 'grid' }, svg), axis = svgEl('g', { class: 'axis' }, svg);
  const yt = o.yLog ? [0.1, 0.3, 1, 3, 10, 30, 100, 300].filter(v => Math.log10(v) >= y0 - 1e-9 && Math.log10(v) <= y1 + 1e-9)
                    : niceTicks(y0, y1, o.yTicks || 5);
  yt.forEach(v => {
    svgEl('line', { x1: m.l, x2: W - m.r, y1: Y(v), y2: Y(v) }, grid);
    text(svg, m.l - 8, Y(v) + 4, (o.fmtY || (t => t))(v), { 'text-anchor': 'end' });
  });
  const xt = o.xTicks || niceTicks(x0, x1, 6);
  xt.forEach(v => {
    svgEl('line', { x1: X(v), x2: X(v), y1: m.t, y2: H - m.b }, grid);
    text(svg, X(v), H - m.b + 16, (o.fmtX || (t => t))(v), { 'text-anchor': 'middle' });
  });
  svgEl('line', { x1: m.l, x2: W - m.r, y1: H - m.b, y2: H - m.b }, axis);
  if (o.xLabel) text(svg, (m.l + W - m.r) / 2, H - 6, o.xLabel, { 'text-anchor': 'middle', class: 'axis-label' });
  if (o.yLabel) text(svg, 14, (m.t + H - m.b) / 2, o.yLabel, { 'text-anchor': 'middle', class: 'axis-label', transform: `rotate(-90 14 ${(m.t + H - m.b) / 2})` });
  if (o.zoneBelow != null) {
    svgEl('rect', { x: m.l, y: Y(o.zoneBelow), width: W - m.l - m.r, height: H - m.b - Y(o.zoneBelow), class: 'zone' }, svg);
  }
  (o.refLines || []).forEach(r => {
    if (r.y != null) {
      svgEl('line', { x1: m.l, x2: W - m.r, y1: Y(r.y), y2: Y(r.y), class: 'ref-line', style: r.color ? `stroke:${r.color}` : '' }, svg);
      text(svg, r.labelLeft ? m.l + 6 : W - m.r - 4, Y(r.y) + (r.labelBelow ? 14 : -6), r.label, { 'text-anchor': r.labelLeft ? 'start' : 'end' });
    } else {
      svgEl('line', { x1: X(r.x), x2: X(r.x), y1: m.t, y2: H - m.b, class: 'ref-line', style: r.color ? `stroke:${r.color}` : '' }, svg);
      text(svg, X(r.x) + 5, m.t + 12, r.label);
    }
  });
  const clipY = v => Math.max(m.t, Math.min(H - m.b, Y(v)));
  o.series.forEach(s => {
    const pts = s.x.map((x, i) => [x, s.y[i]]).filter(p => p[1] != null);
    svgEl('path', {
      d: pts.map((p, i) => `${i ? 'L' : 'M'}${X(p[0]).toFixed(1)},${clipY(p[1]).toFixed(1)}`).join(''),
      class: 'series', stroke: s.color, 'stroke-dasharray': s.dash || '', 'stroke-width': s.width || 2.2,
      opacity: s.opacity || 1,
    }, svg);
    if (s.dots !== false) {
      const g = svgEl('g', {}, svg);
      pts.forEach(p => {
        if (Y(p[1]) < m.t || Y(p[1]) > H - m.b) return;
        hoverDot(g, X(p[0]), Y(p[1]), s.color,
          `<b>${esc(s.name)}</b><br>${esc(o.xName || 'x')}: ${(o.fmtTipX || o.fmtX || (t => t))(p[0])}<br>${esc(o.yName || 'y')}: ${(o.fmtTipY || (t => (+t).toFixed(3)))(p[1])}`,
          s.dotSize || 3);
      });
    }
  });
  (o.markers || []).forEach(mk => {
    const g = svgEl('g', {}, svg), x = X(mk.x), y = clipY(mk.y), r = 6;
    svgEl('path', { d: `M${x - r},${y - r}L${x + r},${y + r}M${x + r},${y - r}L${x - r},${y + r}`, stroke: mk.color, 'stroke-width': 2.4 }, g);
    const hit = svgEl('circle', { cx: x, cy: y, r: 9, fill: 'transparent' }, g);
    hit.addEventListener('mouseenter', e => showTip(e, mk.tip));
    hit.addEventListener('mousemove', moveTip);
    hit.addEventListener('mouseleave', hideTip);
  });
  if (o.legend !== false) legend(el, o.series.filter(s => s.name && !s.noLegend).map(s => ({ name: s.name, color: s.color })));
}

/* ═══════════════════════ Bar chart ═══════════════════════ */
function barChart(el, o) {
  el.innerHTML = '';
  const W = Math.max(300, el.clientWidth || o.width || 620), H = o.height || 290, m = { t: 24, r: 14, b: 46, l: 54 };
  const svg = svgEl('svg', { viewBox: `0 0 ${W} ${H}` }, el);
  const n = o.cats.length, gCount = o.stacked ? 1 : o.groups.length;
  const totals = o.cats.map((_, i) => o.stacked ? o.groups.reduce((a, g) => a + (g.values[i] || 0), 0)
                                               : Math.max(...o.groups.map(g => g.values[i] || 0)));
  const yMax = o.yMax || Math.max(...totals) * 1.15;
  const Y = v => H - m.b - v / yMax * (H - m.t - m.b);
  const grid = svgEl('g', { class: 'grid' }, svg);
  niceTicks(0, yMax, 5).forEach(v => {
    svgEl('line', { x1: m.l, x2: W - m.r, y1: Y(v), y2: Y(v) }, grid);
    text(svg, m.l - 8, Y(v) + 4, (o.fmtY || (t => t))(v), { 'text-anchor': 'end' });
  });
  const band = (W - m.l - m.r) / n, bw = Math.min(46, band * 0.72 / gCount);
  if (o.yLabel) text(svg, 14, (m.t + H - m.b) / 2, o.yLabel, { 'text-anchor': 'middle', class: 'axis-label', transform: `rotate(-90 14 ${(m.t + H - m.b) / 2})` });
  o.cats.forEach((cat, i) => {
    const cx = m.l + band * (i + 0.5);
    const lines = String(cat).split('\n');
    lines.forEach((ln, j) => text(svg, cx, H - m.b + 16 + j * 13, ln, { 'text-anchor': 'middle' }));
    let acc = 0;
    o.groups.forEach((g, gi) => {
      const v = g.values[i];
      if (v == null) {
        if (!o.stacked) text(svg, cx - bw * gCount / 2 + bw * (gi + 0.5), Y(0) - 6, 'OOM', { 'text-anchor': 'middle', class: 'value', style: 'fill:var(--rose)' });
        return;
      }
      const x = o.stacked ? cx - bw / 2 : cx - bw * gCount / 2 + bw * gi;
      const y0 = o.stacked ? Y(acc + v) : Y(v), h = o.stacked ? Y(acc) - Y(acc + v) : Y(0) - Y(v);
      const color = (g.colors && g.colors[i]) || g.color;
      const rect = svgEl('rect', { x: x + 1, y: y0, width: bw - 2, height: Math.max(0.5, h), rx: 3, fill: color, opacity: g.opacity || 1 }, svg);
      rect.addEventListener('mouseenter', e => showTip(e, `<b>${esc(String(cat).replace('\n', ' '))}</b><br>${esc(g.name)}: ${(o.fmtTip || o.fmtVal || (t => t))(v)}`));
      rect.addEventListener('mousemove', moveTip);
      rect.addEventListener('mouseleave', hideTip);
      if (!o.stacked && o.showValues !== false) text(svg, x + bw / 2, y0 - 5, (o.fmtVal || (t => t))(v), { 'text-anchor': 'middle', class: 'value' });
      acc += o.stacked ? v : 0;
    });
    if (o.stacked && o.totalLabels) text(svg, cx, Y(totals[i]) - 6, o.totalLabels[i], { 'text-anchor': 'middle', class: 'value' });
  });
  svgEl('line', { x1: m.l, x2: W - m.r, y1: Y(0), y2: Y(0), stroke: 'var(--border)' }, svg);
  if (o.legend !== false) legend(el, o.groups.filter(g => g.name).map(g => ({ name: g.name, color: g.color })));
}

/* ═══════════════════════ Donut ═══════════════════════ */
function donut(el, title, parts, center, sub) {
  const wrap = document.createElement('div');
  wrap.className = 'donut-wrap';
  const svg = svgEl('svg', { viewBox: '0 0 120 120' });
  const total = parts.reduce((a, p) => a + p.value, 0);
  let a0 = -Math.PI / 2;
  parts.forEach(p => {
    const a1 = a0 + p.value / total * Math.PI * 2, large = a1 - a0 > Math.PI ? 1 : 0;
    const R = 54, r = 34, c = 60;
    const P = (a, rad) => `${c + rad * Math.cos(a)},${c + rad * Math.sin(a)}`;
    const path = svgEl('path', {
      d: `M${P(a0, R)}A${R},${R} 0 ${large} 1 ${P(a1, R)}L${P(a1, r)}A${r},${r} 0 ${large} 0 ${P(a0, r)}Z`,
      fill: p.color, stroke: 'var(--bg-card)', 'stroke-width': 1.5,
    }, svg);
    path.addEventListener('mouseenter', e => showTip(e, `<b>${esc(p.name)}</b><br>${p.value.toFixed(2)} GB · ${(p.value / total * 100).toFixed(0)}%`));
    path.addEventListener('mousemove', moveTip);
    path.addEventListener('mouseleave', hideTip);
    a0 = a1;
  });
  text(svg, 60, 60, center, { 'text-anchor': 'middle', class: 'donut-center' });
  text(svg, 60, 75, sub, { 'text-anchor': 'middle', class: 'donut-sub' });
  wrap.appendChild(svg);
  const lg = document.createElement('div');
  lg.className = 'donut-legend';
  lg.innerHTML = `<strong style="color:var(--text-primary);font-size:13px">${esc(title)}</strong>` +
    parts.map(p => `<span><i style="background:${p.color}"></i>${esc(p.name)} — ${p.value.toFixed(2)} GB (${(p.value / total * 100).toFixed(0)}%)</span>`).join('');
  wrap.appendChild(lg);
  el.appendChild(wrap);
}

/* ═══════════════════════ Hero + glance ═══════════════════════ */
function renderHero() {
  $('#hero-stats').innerHTML = D.heroStats.map(s =>
    `<div class="hero-stat"><span class="val ${s.cls || ''}">${esc(s.val)}</span><span class="lbl">${esc(s.lbl)}</span></div>`).join('');
}

function renderGlance() {
  const runs = [L.base, L.mid, L.eul, L.x2, L.x4, L.x8].map(l => RUN[l]).filter(Boolean);
  const best = (key, dir) => (dir === 'min' ? Math.min : Math.max)(...runs.map(r => r[key]));
  const b = { valLoss: best('valLoss', 'min'), valAcc: best('valAcc', 'max'), tokensPerSec: best('tokensPerSec', 'max'),
              peakGB: best('peakGB', 'min'), wallMin: best('wallMin', 'min'), actPerSeqMB: best('actPerSeqMB', 'min'), mfu: best('mfu', 'max') };
  const cls = (k, v) => Math.abs(v - b[k]) < 1e-9 ? 'best' : '';
  $('#glance-table').innerHTML = `
    <thead><tr><th>#</th><th class="l">Run</th><th>Batch</th><th>Steps</th><th>Val loss</th><th>Val ppl</th><th>Val acc</th>
      <th>Tokens/s</th><th>MFU</th><th>Peak GB</th><th>Act MB/seq</th><th>Wall min</th></tr></thead>
    <tbody>${runs.map((r, i) => `
      <tr class="${r.label === L.eul ? 'hl' : ''}">
        <td>${i + 1}</td><td class="name l">${esc(SHORT[r.label])}${r.label === L.eul ? ' 🏆' : ''}</td>
        <td>${r.batch}</td><td>${r.steps}</td>
        <td class="${cls('valLoss', r.valLoss)}">${r.valLoss.toFixed(3)}</td><td>${r.valPpl.toFixed(1)}</td>
        <td class="${cls('valAcc', r.valAcc)}">${fmt.pct(r.valAcc, 2)}</td>
        <td class="${cls('tokensPerSec', r.tokensPerSec)}">${fmt.k(r.tokensPerSec)}</td>
        <td class="${cls('mfu', r.mfu)}">${fmt.pct(r.mfu)}</td>
        <td class="${cls('peakGB', r.peakGB)}">${r.peakGB.toFixed(2)}</td>
        <td class="${cls('actPerSeqMB', r.actPerSeqMB)}">${r.actPerSeqMB.toFixed(1)}</td>
        <td class="${cls('wallMin', r.wallMin)}">${r.wallMin.toFixed(1)}</td>
      </tr>`).join('')}</tbody>`;
}

/* ═══════════════════════ 1. Theory ═══════════════════════ */
function renderTheory() {
  const steps = [
    ['Forward, no graph', 'Run all 9 cells under no_grad. Nothing per layer is kept; each state is freed as soon as the next one exists.'],
    ['Store only the end', 'Autograd keeps just the final pair of streams (q, p) or (p⁽ᴸ⁻¹⁾, p⁽ᴸ⁾): 3.0 MB per sequence, independent of depth.'],
    ['Walk backward, one cell at a time', 'Each cell evaluates its sub-layer once, and that single evaluation both reconstructs the previous state and yields the vector-Jacobian product.'],
    ['Free and repeat', 'The cell\'s temporary graph is dropped before moving to the previous layer, so only one layer\'s working set is alive at any time.'],
    ['Exact by construction', 'Streams are float64 and every update is rounded to a 2⁻³⁰ grid, so subtraction recovers each state bit-for-bit.'],
  ];
  $('#theory-flow').innerHTML = steps.map((s, i) =>
    `<div class="flow-step"><div class="flow-n">0${i + 1}</div><div class="flow-body"><h4>${s[0]}</h4><p>${s[1]}</p></div></div>`).join('');
}

/* ═══════════════════════ 2. Correctness ═══════════════════════ */
function renderCorrect() {
  const fixes = [
    ['badge-red', 'Memory', 'One autograd Function per layer → one for the whole stack',
      'Each per-layer Function called save_for_backward, so every layer\'s output stayed alive until backward: the same memory as the baseline.',
      'Stored activations now flat in depth: 74 MB from 3 to 24 layers.'],
    ['badge-yellow', 'Speed', 'Inverse + re-run → one sub-layer evaluation per step',
      'Backward ran inverse() and then re-ran step() under autograd, i.e. two extra forward passes per layer. It now runs one, RevNet-style.',
      'Reversible step 304 → 178 ms in local tests (−42%).'],
    ['badge-purple', 'Precision', 'Backward now runs under the forward\'s autocast',
      'PyTorch runs backward outside autocast, so the reconstruction recomputed layers in fp32 while the forward had used bf16. That was slow and inexact.',
      'custom_fwd / custom_bwd keep both passes in bf16.'],
    ['badge-green', 'Exactness', 'float64 fixed-point residual streams',
      'Even with matched precision, (x + u) − u ≠ x in floating point, and bf16 rounding flips amplify the error layer by layer.',
      'Reconstruction error exactly 0 in all 4 reversible training runs.'],
  ];
  $('#fix-cards').innerHTML = fixes.map(f =>
    `<div class="fix-card"><span class="badge ${f[0]}">${f[1]}</span><h4>${f[2]}</h4><p>${f[3]}</p><div class="impact">✓ ${f[4]}</div></div>`).join('');

  const diag = D.tables.reversibility_diagnostics || [];
  const cats = diag.map(d => `${d.variant}\n${d.streams.startsWith('exact') ? 'exact' : 'fp32'} · w×${d.weight_scale}`);
  barChart($('#chart-exact'), {
    cats, height: 270, yMax: 1.1,
    groups: [{ name: 'gradient cosine vs autograd (1.0 = identical)', color: '#10b981',
               colors: diag.map(d => d.streams.startsWith('exact') ? '#10b981' : '#f43f5e'), values: diag.map(d => d.grad_cosine) }],
    fmtVal: v => v.toFixed(3), fmtY: v => v.toFixed(1), legend: false,
  });
  legend($('#chart-exact'), [{ name: 'exact float64 fixed-point streams', color: '#10b981' }, { name: 'plain fp32 streams', color: '#f43f5e' }]);
}

/* ═══════════════════════ 3. Setup ═══════════════════════ */
function kv(sel, rows) { $(sel).innerHTML = rows.map(([k, v]) => `<tr><th>${k}</th><td>${v}</td></tr>`).join(''); }
function renderSetup() {
  kv('#kv-model', [['Parameters', '20,105,216'], ['Layers × width × heads', '9 × 256 × 8'], ['Context', '512 tokens'],
                   ['Vocab (tied)', '50,257 (64% of params)'], ['Midpoint h', '0.25'], ['Reversal', 'exact (fp64 grid)']]);
  kv('#kv-data', [['Dataset', 'WikiText-103 raw'], ['Tokenizer', 'GPT-2 BPE'], ['Train split', '119.1M tokens'],
                  ['Budget / run', '50M (0.42 epochs)'], ['Val (final)', 'full split, 249k tok'], ['Periodic eval', 'every 2.5M tokens']]);
  kv('#kv-train', [['Optimizer', 'AdamW (fused), wd 0.1'], ['Peak LR at x', '1e-3'], ['Schedule', '5% warmup → cosine'],
                   ['LR at 2x/4x/8x', '× √(batch/x)'], ['Precision', 'bf16 autocast'], ['GPU', `${esc(D.meta.gpu || '')} ${D.meta.gpuMemoryGB || ''} GB`]]);
  const probe = D.tables.probe_peak_memory_mb || {};
  const act = D.tables.probe_activation_mb_per_seq || {};
  const tps = D.tables.probe_tokens_per_sec || {};
  const bs = Object.keys(probe);
  const cell = v => v == null ? '<span class="worst">OOM</span>' : (v / 1024).toFixed(2);
  $('#probe-table').innerHTML = `
    <thead><tr><th class="l">Batch</th><th>Baseline</th><th>Midpoint</th><th>Euler</th><th>Act MB/seq (base / rev)</th><th>Probe tok/s (base / Euler)</th><th class="l">Role</th></tr></thead>
    <tbody>${bs.map(b => `<tr class="${b === '128' ? 'hl' : ''}"><td class="name l">${b}</td>
      <td>${cell(probe[b].baseline)}</td><td>${cell(probe[b].midpoint)}</td><td>${cell(probe[b].euler)}</td>
      <td>${act[b].baseline == null ? '—' : act[b].baseline.toFixed(1)} / ${act[b].euler.toFixed(1)}</td>
      <td>${tps[b].baseline == null ? '—' : fmt.k(tps[b].baseline)} / ${fmt.k(tps[b].euler)}</td>
      <td class="name l" style="font-weight:500;color:var(--text-muted)">${{ 64: 'x/2', 128: 'x (exp 1-3)', 256: '2x (exp 4)', 512: '4x (exp 5)', 1024: '8x (exp 6)' }[b] || ''}</td></tr>`).join('')}</tbody>`;
}

/* ═══════════════════════ 4. Race ═══════════════════════ */
let raceAxis = 'tokens';
function renderRace() {
  const three = [L.base, L.mid, L.eul];
  const series = three.map(l => {
    const c = D.curves[l], v = RUN[l].variant;
    return { name: `${SHORT[l]} (final ${RUN[l].valLoss.toFixed(3)})`, color: COLORS[v],
             x: (raceAxis === 'tokens' ? c.evalTokensM : c.evalWallMin).slice(1), y: c.valLoss.slice(1) };
  });
  const baseEnd = D.curves[L.base].evalWallMin.at(-1);
  lineChart($('#chart-race'), {
    series, yMin: 4.7, yMax: 7.3, xMin: 0, xLabel: raceAxis === 'tokens' ? 'training tokens (M)' : 'wall clock (min)',
    yLabel: 'val loss', xName: raceAxis === 'tokens' ? 'tokens (M)' : 'minutes', yName: 'val loss',
    fmtX: v => raceAxis === 'tokens' ? v : v.toFixed(0), fmtTipX: v => (+v).toFixed(2),
    refLines: raceAxis === 'time' ? [{ x: baseEnd, label: 'baseline done', color: '#64748b' }] : [],
  });
  $('#race-title').textContent = raceAxis === 'tokens' ? 'Validation loss vs training tokens' : 'Validation loss vs wall-clock time';

  const bc = D.curves[L.base];
  lineChart($('#chart-delta'), {
    series: [L.mid, L.eul].map(l => ({
      name: SHORT[l], color: COLORS[RUN[l].variant], x: D.curves[l].evalTokensM.slice(1),
      y: D.curves[l].valLoss.slice(1).map((v, i) => v - bc.valLoss[i + 1]),
    })),
    yMin: -0.08, yMax: 0.18, xMin: 0, zoneBelow: 0, xLabel: 'training tokens (M)', yLabel: 'Δ val loss',
    refLines: [{ y: 0, label: '', color: '#64748b' }], xName: 'tokens (M)', yName: 'Δ vs baseline',
    fmtY: v => v.toFixed(2), fmtTipY: v => (v >= 0 ? '+' : '') + (+v).toFixed(3),
  });
}

/* ═══════════════════════ 5. Memory ═══════════════════════ */
function renderMemory() {
  const three = [L.base, L.mid, L.eul].map(l => RUN[l]);
  barChart($('#chart-mem'), {
    cats: three.map(r => SHORT[r.label]),
    groups: [
      { name: 'per-step peak', color: '#6366f1', colors: three.map(r => COLORS[r.variant]), values: three.map(r => r.peakGB) },
      { name: 'stored for backward', color: '#22d3ee', values: three.map(r => r.savedGB), opacity: 0.8 },
    ],
    fmtVal: v => v.toFixed(2), fmtY: v => v, yLabel: 'GB', legend: false,
  });
  legend($('#chart-mem'), [{ name: 'per-step peak (variant colour)', color: '#94a3b8' }, { name: 'activations stored for backward', color: '#22d3ee' }]);

  const depth = D.tables.depth_saved_activation_mb || {};
  const Ls = Object.keys(depth).map(Number);
  lineChart($('#chart-depth'), {
    series: ['baseline', 'midpoint', 'euler'].map(v => ({
      name: v, color: COLORS[v], x: Ls, y: Ls.map(n => depth[n][v]), dash: v === 'euler' ? '6 4' : '',
    })),
    yMin: 0, xTicks: Ls, xLabel: 'number of layers', yLabel: 'MB stored', xName: 'layers', yName: 'MB', fmtTipY: v => (+v).toFixed(1),
  });

  const box = $('#donuts-mem');
  box.innerHTML = '';
  [[L.base, 'Baseline, batch 128'], [L.eul, 'Euler, batch 128']].forEach(([l, title]) => {
    const r = RUN[l];
    donut(box, title, [
      { name: 'params + AdamW state', value: r.staticGB, color: '#10b981' },
      { name: 'stored activations', value: r.savedGB, color: '#6366f1' },
      { name: 'transient (backward working set, loss chunk)', value: r.peakGB - r.staticGB - r.savedGB, color: '#f59e0b' },
    ], r.peakGB.toFixed(2), 'GB peak');
  });
}

/* ═══════════════════════ 6. Speed ═══════════════════════ */
function renderSpeed() {
  const labels = [L.base, L.mid, L.eul, L.x2, L.x4, L.x8];
  const runs = labels.map(l => RUN[l]);
  const per = (r, k) => r[k] / r.batch * 128;  // ms per 65,536 tokens
  barChart($('#chart-phases'), {
    cats: runs.map(r => SHORT[r.label].replace(' ', '\n')), stacked: true, height: 300,
    groups: [
      { name: 'data', color: '#94a3b8', values: runs.map(r => per(r, 'dataMs')) },
      { name: 'forward (+ fused loss grad)', color: '#6366f1', values: runs.map(r => per(r, 'forwardMs')) },
      { name: 'backward (+ recompute)', color: '#f59e0b', values: runs.map(r => per(r, 'backwardMs')) },
      { name: 'optimizer', color: '#10b981', values: runs.map(r => per(r, 'optimizerMs')) },
    ],
    totalLabels: runs.map(r => fmt.k(r.tokensPerSec) + ' tok/s'), fmtTip: v => v.toFixed(1) + ' ms', yLabel: 'ms / 65,536 tokens', yMax: 680,
  });
  const cost = D.tables.exactness_cost || [];
  const get = (v, s) => (cost.find(c => c.variant === v && c.streams === s) || {})['step ms'];
  const vals = [get('baseline', '-'), get('midpoint', 'plain fp32'), get('midpoint', 'exact fp64'), get('euler', 'plain fp32'), get('euler', 'exact fp64')];
  barChart($('#chart-exactcost'), {
    cats: ['baseline', 'midpoint\nfp32', 'midpoint\nexact', 'euler\nfp32', 'euler\nexact'], height: 300,
    groups: [{ name: 'ms / step', color: '#6366f1', colors: ['#64748b', '#a5b4fc', '#6366f1', '#fcd34d', '#f59e0b'], values: vals }],
    fmtVal: v => v === vals[0] ? `${v.toFixed(0)} ms` : `${v.toFixed(0)} (+${((v / vals[0] - 1) * 100).toFixed(0)}%)`,
    fmtTip: v => v.toFixed(1) + ' ms', legend: false, yLabel: 'ms / training step', yMax: 640,
  });
}

/* ═══════════════════════ 7. Choice ═══════════════════════ */
function renderChoice() {
  const b = RUN[L.base], m = RUN[L.mid], e = RUN[L.eul];
  const card = (r, extra, win) => `
    <div class="verdict-card ${win ? 'win' : ''}">
      <h4>${esc(SHORT[r.label])} <span class="badge ${win ? 'badge-yellow' : 'badge-blue'}">${win ? 'SELECTED' : r.variant === 'baseline' ? 'REFERENCE' : 'RUNNER-UP'}</span></h4>
      <div class="big">${r.valLoss.toFixed(3)}</div><div class="muted">final val loss · ${fmt.k(r.tokensPerSec)} tok/s · ${r.peakGB.toFixed(2)} GB peak</div>
      <p class="fine">${extra}</p></div>`;
  $('#verdict').innerHTML =
    card(b, 'Fastest by far, but needs twice the memory. It cannot run batch 1024 on 48 GB.', false) +
    card(m, `Loss within ${(m.valLoss - b.valLoss).toFixed(3)} of the baseline and 10% faster than Euler. Lost on the pre-registered loss rule (gap ${((m.valLoss - e.valLoss) / m.valLoss * 100).toFixed(2)}% ≥ 1%).`, false) +
    card(e, 'Best loss of all six runs, half the baseline\'s peak memory, exact gradients. The slowest per step.', true);
  const at59 = { mid: 4.895, eul: 4.882 };  // interpolated at the baseline's finishing time (notebook analysis)
  const rows = [
    ['Final val loss', m.valLoss.toFixed(3), e.valLoss.toFixed(3), 'e'],
    ['Val accuracy', fmt.pct(m.valAcc, 2), fmt.pct(e.valAcc, 2), 'e'],
    ['Throughput', fmt.k(m.tokensPerSec) + ' tok/s', fmt.k(e.tokensPerSec) + ' tok/s', 'm'],
    ['Wall clock (50M tokens)', m.wallMin.toFixed(1) + ' min', e.wallMin.toFixed(1) + ' min', 'm'],
    ['Val loss at 5.9 min (baseline done: 4.828)', at59.mid.toFixed(3), at59.eul.toFixed(3), 'e'],
    ['Peak memory', m.peakGB.toFixed(2) + ' GB', e.peakGB.toFixed(2) + ' GB', '='],
    ['Stored activations / seq', m.actPerSeqMB.toFixed(1) + ' MB', e.actPerSeqMB.toFixed(1) + ' MB', '='],
    ['Reconstruction error', String(m.reconError), String(e.reconError), '='],
    ['Grad cosine vs autograd', m.gradCosine.toFixed(7), e.gradCosine.toFixed(7), '='],
    ['Mean grad norm / clipped steps', `${m.gradNormMean.toFixed(2)} / ${fmt.pct(m.clipFrac)}`, `${e.gradNormMean.toFixed(2)} / ${fmt.pct(e.clipFrac)}`, 'm'],
  ];
  $('#choice-table').innerHTML = `<thead><tr><th class="l">Criterion</th><th>Midpoint</th><th>Euler</th><th class="l">Better</th></tr></thead>
    <tbody>${rows.map(r => `<tr><td class="name l">${r[0]}</td><td class="${r[3] === 'm' ? 'best' : ''}">${r[1]}</td>
      <td class="${r[3] === 'e' ? 'best' : ''}">${r[2]}</td><td class="name l">${{ m: 'Midpoint', e: 'Euler', '=': 'tie' }[r[3]]}</td></tr>`).join('')}</tbody>`;
}

/* ═══════════════════════ 8. Scaling ═══════════════════════ */
let scaleView = 'loss';
function renderScaling() {
  const labels = [L.eul, L.x2, L.x4, L.x8];
  if (scaleView === 'loss') {
    const series = labels.map(l => ({ name: `batch ${RUN[l].batch} · ${RUN[l].steps} steps`, color: SCALE_COLORS[RUN[l].batch],
                                      x: D.curves[l].evalTokensM.slice(1), y: D.curves[l].valLoss.slice(1) }));
    series.push({ name: 'baseline, batch 128', color: '#64748b', dash: '5 4', x: D.curves[L.base].evalTokensM.slice(1), y: D.curves[L.base].valLoss.slice(1), dots: false });
    lineChart($('#chart-scale'), { series, yMin: 4.6, yMax: 9.6, xMin: 0, xLabel: 'training tokens (M)', yLabel: 'val loss', xName: 'tokens (M)', yName: 'val loss',
                                   refLines: [{ y: 6, label: 'val loss 6.0: batch 512 and 1024 never get below it', color: '#94a3b8', labelLeft: true, labelBelow: true }] });
    $('#scale-title').textContent = 'Validation loss vs training tokens';
  } else {
    const series = labels.map(l => ({ name: `batch ${RUN[l].batch}`, color: SCALE_COLORS[RUN[l].batch], x: D.curves[l].stepTokensM,
                                      y: D.curves[l].gradNorm, dots: false, width: 1.4 }));
    lineChart($('#chart-scale'), { series, yLog: true, yMin: 0.2, yMax: 300, xMin: 0, xLabel: 'training tokens (M)', yLabel: 'grad norm (log)',
                                   refLines: [{ y: 1, label: 'clip = 1.0', color: '#f43f5e' }], fmtY: v => v });
    $('#scale-title').textContent = 'Gradient norm per step (log scale, down-sampled)';
  }
  const rs = labels.map(l => RUN[l]);
  const cats = rs.map(r => `${r.batch}\n${r.steps} steps`);
  barChart($('#chart-scale-loss'), { cats, height: 250, groups: [{ name: 'val loss', color: '#f43f5e', colors: rs.map(r => SCALE_COLORS[r.batch]), values: rs.map(r => r.valLoss) }],
                                     fmtVal: v => v.toFixed(2), yMax: 8, legend: false });
  barChart($('#chart-scale-tps'), { cats, height: 250, groups: [{ name: 'k tokens/s', color: '#10b981', colors: rs.map(r => SCALE_COLORS[r.batch]), values: rs.map(r => r.tokensPerSec / 1000) }],
                                    fmtVal: v => v.toFixed(1), yMax: 180, legend: false });
  barChart($('#chart-scale-mem'), { cats, height: 250, groups: [{ name: 'peak GB', color: '#6366f1', colors: rs.map(r => SCALE_COLORS[r.batch]), values: rs.map(r => r.peakGB) }],
                                    fmtVal: v => v.toFixed(1), yMax: 20, legend: false });
}

/* ═══════════════════════ 9. Max batch ═══════════════════════ */
function renderMaxBatch() {
  const rows = D.tables.max_batch_search || [];
  const gpu = D.meta.gpuMemoryGB || 48;
  const series = [], markers = [];
  ['baseline', 'euler'].forEach(v => {
    const ok = rows.filter(r => r.variant === v && r.fits).sort((a, b) => a.batch_size - b.batch_size);
    series.push({ name: `${v}: max batch ${D.tables.max_batch[v]}`, color: COLORS[v], x: ok.map(r => r.batch_size), y: ok.map(r => r.peak_memory_mb / 1024) });
    rows.filter(r => r.variant === v && !r.fits).forEach(r => markers.push({ x: r.batch_size, y: gpu, color: COLORS[v], tip: `<b>${v}</b><br>batch ${r.batch_size}: out of memory` }));
  });
  const exp = [L.eul, L.x2, L.x4, L.x8].map(l => RUN[l]);
  series.push({ name: 'experiments 3-6 (measured in training)', color: '#10b981', x: exp.map(r => r.batch), y: exp.map(r => r.peakGB), dash: '2 5', dotSize: 5 });
  lineChart($('#chart-maxbatch'), {
    series, markers, yMin: 0, yMax: gpu + 3, xMin: 0, xMax: 4200, height: 330,
    xLabel: 'batch size (sequences of 512 tokens)', yLabel: 'peak memory (GB)', xName: 'batch', yName: 'GB',
    refLines: [{ y: gpu, label: `GPU memory ${gpu} GB`, color: '#f43f5e', labelLeft: true, labelBelow: true }], fmtTipY: v => (+v).toFixed(1),
  });
}

/* ═══════════════════════ 10. Conclusions ═══════════════════════ */
function renderConclusions() {
  const findings = [
    '<strong>Reversibility works as advertised for memory:</strong> −51% peak, 14x fewer stored activations, and flat in depth (74 MB at 3 or 24 layers).',
    '<strong>Euler was the best model of the six</strong> (val loss 4.774 vs 4.828) and reached the baseline\'s final loss with 15% fewer tokens. Midpoint matched the baseline (+0.014).',
    '<strong>It costs throughput:</strong> −18% (midpoint) and −26% (Euler). About half of that is exact fp64 reversal on a GPU with slow fp64.',
    '<strong>Maximum batch grew 2.8x</strong> (896 → 2528). Batch 1024, impossible for the baseline, trained in 16.4 GB.',
    '<strong>Bigger batches hurt at a fixed token budget:</strong> the loss rose from 4.77 to 6.75 at 8x, for only +6.6% throughput.',
    '<strong>Exact reversal is non-negotiable:</strong> plain fp32 streams gave gradient cosines of 0.50-0.63 on sharpened weights.',
  ];
  const recs = [
    '<strong>To fit a bigger model, use reversible Euler with exact streams.</strong> It halves the memory and does not hurt quality here.',
    '<strong>When memory is not the limit and wall-clock speed matters,</strong> keep the standard transformer.',
    '<strong>Spend the saved memory on depth, context or width,</strong> not on a batch beyond the critical batch size.',
    '<strong>Next:</strong> 2-3 seeds to confirm the Euler gain; a deeper, narrower model (24-48 layers); a cheaper exact scheme (int32 fixed-point) or a GPU with fast fp64; longer warmup or a larger budget for large-batch runs.',
  ];
  $('#conc-findings').innerHTML = findings.map(f => `<li>${f}</li>`).join('');
  $('#conc-recs').innerHTML = recs.map(f => `<li>${f}</li>`).join('');

  // Trade-off scatter: x = peak GB, y = k tok/s, radius grows as loss improves.
  const el = $('#chart-tradeoff');
  el.innerHTML = '';
  const W = Math.max(360, el.clientWidth || 900), H = 340, m = { t: 16, r: 20, b: 42, l: 56 };
  const svg = svgEl('svg', { viewBox: `0 0 ${W} ${H}` }, el);
  const runs = D.runs.filter(r => r.status === 'ok');
  const X = v => m.l + v / 18 * (W - m.l - m.r), Y = v => H - m.b - (v - 100) / 70 * (H - m.t - m.b);
  const grid = svgEl('g', { class: 'grid' }, svg);
  [0, 3, 6, 9, 12, 15, 18].forEach(v => { svgEl('line', { x1: X(v), x2: X(v), y1: m.t, y2: H - m.b }, grid); text(svg, X(v), H - m.b + 16, v, { 'text-anchor': 'middle' }); });
  [100, 120, 140, 160].forEach(v => { svgEl('line', { x1: m.l, x2: W - m.r, y1: Y(v), y2: Y(v) }, grid); text(svg, m.l - 8, Y(v) + 4, v, { 'text-anchor': 'end' }); });
  text(svg, (m.l + W - m.r) / 2, H - 6, 'peak memory (GB)', { 'text-anchor': 'middle', class: 'axis-label' });
  text(svg, 14, H / 2, 'k tokens / s', { 'text-anchor': 'middle', class: 'axis-label', transform: `rotate(-90 14 ${H / 2})` });
  const g = svgEl('g', {}, svg);
  runs.forEach(r => {
    const color = r.variant === 'euler' && r.batch > 128 ? SCALE_COLORS[r.batch] : COLORS[r.variant];
    const rad = 6 + Math.max(0, (7 - r.valLoss)) * 7;
    const cx = X(r.peakGB), cy = Y(r.tokensPerSec / 1000);
    svgEl('circle', { cx, cy, r: rad, fill: color, opacity: 0.25, stroke: color, 'stroke-width': 1.5 }, g);
    // Hand-placed offsets: midpoint, Euler and Euler 2x sit within 0.5 GB of each other.
    const off = { [L.mid]: [-rad - 4, -rad - 2, 'end'], [L.eul]: [-rad - 4, rad + 10, 'end'], [L.x2]: [rad + 4, 4, 'start'] }[r.label] || [rad + 4, 4, 'start'];
    text(svg, cx + off[0], cy + off[1], `${SHORT[r.label]} · ${r.valLoss.toFixed(2)}`, { class: 'value', 'text-anchor': off[2] });
    hoverDot(g, cx, cy, color, `<b>${SHORT[r.label]}</b><br>val loss ${r.valLoss.toFixed(3)}<br>${fmt.k(r.tokensPerSec)} tok/s · ${r.peakGB.toFixed(2)} GB`, 4);
  });
}

/* ═══════════════════════ Reproduce ═══════════════════════ */
function renderRepro() {
  kv('#kv-artifacts', [
    ['Per-run records', 'notebooks/results/exp*.json'], ['Summary table', 'results/final_comparison.csv'],
    ['Text + step logs', 'notebooks/logs/*.log, *.metrics.jsonl'], ['Aim runs', `${D.runs.length} runs · experiment session13_reversible_llm`],
    ['README figures', 'scripts/make_figures.py → assets/'], ['This page\'s data', 'revllm.export → webapp/data.js'],
  ]);
}

/* ═══════════════════════ Navigation / progress / reveal ═══════════════════════ */
function initNav() {
  const items = $$('.nav-item');
  const sections = items.map(a => document.getElementById(a.dataset.target)).filter(Boolean);
  const onScroll = () => {
    const y = window.scrollY + 120;
    let current = sections[0];
    sections.forEach(s => { if (s.offsetTop <= y) current = s; });
    items.forEach(a => a.classList.toggle('active', a.dataset.target === current.id));
    const h = document.documentElement;
    $('#reading-progress').style.width = (h.scrollTop / (h.scrollHeight - h.clientHeight) * 100) + '%';
  };
  window.addEventListener('scroll', onScroll, { passive: true });
  onScroll();
  const obs = new IntersectionObserver(es => es.forEach(e => { if (e.isIntersecting) e.target.classList.add('visible'); }), { threshold: 0.08 });
  $$('.card, .fix-card, .verdict-card, .callout').forEach(c => { c.classList.add('reveal-item'); obs.observe(c); });
}
function initTabs() {
  const tab = (a, b, set) => {
    $(a).addEventListener('click', () => { $(a).classList.add('active'); $(b).classList.remove('active'); set(); });
  };
  tab('#race-tokens', '#race-time', () => { raceAxis = 'tokens'; renderRace(); });
  tab('#race-time', '#race-tokens', () => { raceAxis = 'time'; renderRace(); });
  tab('#scale-loss', '#scale-gn', () => { scaleView = 'loss'; renderScaling(); });
  tab('#scale-gn', '#scale-loss', () => { scaleView = 'gn'; renderScaling(); });
}

const CHARTS = [renderCorrect, renderRace, renderMemory, renderSpeed, renderScaling, renderMaxBatch, renderConclusions];
document.addEventListener('DOMContentLoaded', () => {
  renderHero(); renderGlance(); renderTheory(); renderSetup(); renderChoice(); renderRepro();
  CHARTS.forEach(f => f());
  initTabs(); initNav();
  // Charts are drawn at their container's pixel width; redraw when it changes.
  let timer, lastW = window.innerWidth;
  window.addEventListener('resize', () => {
    clearTimeout(timer);
    timer = setTimeout(() => { if (window.innerWidth !== lastW) { lastW = window.innerWidth; CHARTS.forEach(f => f()); } }, 150);
  });
});
